<?php

declare(strict_types=1);

use Igne\LaravelBootUp\Deploy\ProjectCommand;
use Igne\LaravelBootUp\Deploy\Scripts\DeploymentEnvironment;
use Igne\LaravelBootUp\Deploy\Scripts\DeploymentPlan;
use Igne\LaravelBootUp\Deploy\Scripts\ForgeScriptGenerator;
use Igne\LaravelBootUp\Frontend\PackageManager;

function forgePlan(array $overrides = []): DeploymentPlan
{
    $defaults = [
        'environment' => DeploymentEnvironment::PRODUCTION,
        'migrate' => true,
        'finalize' => ['storage:link'],
        'beforeMigrations' => [],
        'afterMigrations' => [],
        'frontend' => true,
        'packageManager' => PackageManager::NPM,
        'restartQueues' => true,
        'zeroDowntime' => true,
    ];

    return new DeploymentPlan(...array_merge($defaults, $overrides));
}

test('renders the full zero-downtime production script', function (): void {
    $script = (new ForgeScriptGenerator)->generate(forgePlan([
        'beforeMigrations' => [ProjectCommand::artisan('wayfinder:generate', 'Generating routes...')],
    ]));

    expect($script)->toBe(<<<'SCRIPT'
# Laravel Forge deployment script (production, zero-downtime)
# Generated by igne-agency/laravel-boot-up — paste into Forge → your site → Deployments.
# Requires a site created WITH zero-downtime deployments; the $CREATE_RELEASE()/$ACTIVATE_RELEASE()
# macros do not work on classic sites (regenerate with --classic for those).

$CREATE_RELEASE()

cd $FORGE_RELEASE_DIRECTORY

$FORGE_COMPOSER install --no-dev --no-interaction --prefer-dist --optimize-autoloader

$FORGE_PHP artisan optimize
$FORGE_PHP artisan storage:link
# Generating routes...
$FORGE_PHP artisan wayfinder:generate
$FORGE_PHP artisan migrate --force

npm ci || npm install
npm run build

$ACTIVATE_RELEASE()

$RESTART_QUEUES()

SCRIPT);
});

test('each package manager gets its lockfile-strict install line', function (PackageManager $manager, string $line): void {
    $script = (new ForgeScriptGenerator)->generate(forgePlan(['packageManager' => $manager]));

    expect($script)->toContain($line)
        ->and($script)->toContain("{$manager->value} run build");
})->with([
    'npm' => [PackageManager::NPM, 'npm ci || npm install'],
    'pnpm' => [PackageManager::PNPM, 'pnpm install --frozen-lockfile || pnpm install'],
    'yarn' => [PackageManager::YARN, 'yarn install --frozen-lockfile || yarn install'],
    'bun' => [PackageManager::BUN, 'bun install --frozen-lockfile || bun install'],
]);

test('development keeps dev dependencies and skips framework caching', function (): void {
    $script = (new ForgeScriptGenerator)->generate(forgePlan([
        'environment' => DeploymentEnvironment::DEVELOPMENT,
    ]));

    expect($script)->toContain('$FORGE_COMPOSER install --no-interaction')
        ->and($script)->not->toContain('--no-dev')
        ->and($script)->not->toContain('artisan optimize');
});

test('config toggles drop their lines', function (): void {
    $script = (new ForgeScriptGenerator)->generate(forgePlan([
        'migrate' => false,
        'frontend' => false,
        'restartQueues' => false,
        'finalize' => [],
    ]));

    expect($script)->not->toContain('migrate --force')
        ->and($script)->not->toContain('run build')
        ->and($script)->not->toContain('$RESTART_QUEUES()')
        ->and($script)->not->toContain('storage:link');
});

test('after-migration project commands render after migrate with composer and package-manager types', function (): void {
    $script = (new ForgeScriptGenerator)->generate(forgePlan([
        'afterMigrations' => [
            ProjectCommand::composer('dump-autoload --optimize'),
            ProjectCommand::packageManager('run zodgen'),
        ],
        'packageManager' => PackageManager::PNPM,
    ]));

    $migratePosition = strpos($script, 'migrate --force');

    expect(strpos($script, '$FORGE_COMPOSER dump-autoload --optimize'))->toBeGreaterThan($migratePosition)
        ->and($script)->toContain('pnpm run zodgen');
});

test('the classic variant uses git pull and the fpm reload block instead of macros', function (): void {
    $script = (new ForgeScriptGenerator)->generate(forgePlan([
        'frontend' => false,
        'zeroDowntime' => false,
    ]));

    expect($script)->toBe(<<<'SCRIPT'
# Laravel Forge deployment script (production, classic)
# Generated by igne-agency/laravel-boot-up — paste into Forge → your site → Deployments.
# For sites WITHOUT zero-downtime deployments (no release macros available).

cd $FORGE_SITE_PATH

git pull origin $FORGE_SITE_BRANCH

$FORGE_COMPOSER install --no-dev --no-interaction --prefer-dist --optimize-autoloader

$FORGE_PHP artisan optimize
$FORGE_PHP artisan storage:link
$FORGE_PHP artisan migrate --force

$FORGE_PHP artisan queue:restart

# Prevent concurrent PHP-FPM reloads...
touch /tmp/fpmlock 2>/dev/null || true

(
    flock -w 10 9 || exit 1

    echo 'Reloading PHP-FPM...'
    sudo -S service $FORGE_PHP_FPM reload
) 9</tmp/fpmlock

SCRIPT);
});
