<?php

declare(strict_types=1);

use Igne\LaravelBootUp\Deploy\ProjectCommand;
use Igne\LaravelBootUp\Deploy\Scripts\DeploymentEnvironment;
use Igne\LaravelBootUp\Deploy\Scripts\DeploymentPlan;
use Igne\LaravelBootUp\Deploy\Scripts\FortrabbitScriptGenerator;
use Igne\LaravelBootUp\Frontend\PackageManager;

function fortrabbitPlan(array $overrides = []): DeploymentPlan
{
    $defaults = [
        'environment' => DeploymentEnvironment::PRODUCTION,
        'migrate' => true,
        'finalize' => ['storage:link'],
        'beforeMigrations' => [],
        'afterMigrations' => [],
        'frontend' => true,
        'packageManager' => PackageManager::PNPM,
        'restartQueues' => true,
    ];

    return new DeploymentPlan(...array_merge($defaults, $overrides));
}

test('renders build and post-deploy sections for production with pnpm', function (): void {
    $script = (new FortrabbitScriptGenerator)->generate(fortrabbitPlan());

    expect($script)->toBe(<<<'SCRIPT'
# Fortrabbit deployment commands (production)
# Generated by igne-agency/laravel-boot-up.
# Paste each section into the fortrabbit dashboard → your App →
# Deployment settings for the production environment.

# ─── Build commands ────────────────────────────────────────────
composer install --no-dev --prefer-dist --no-interaction --no-ansi --no-progress
npm i -g pnpm
pnpm install --frozen-lockfile || pnpm install
pnpm run build

# ─── Post deploy commands ──────────────────────────────────────
php artisan migrate --force
php artisan optimize
php artisan storage:link
php artisan queue:restart

SCRIPT);
});

test('renders bound commands for all four phases in the canonical order', function (): void {
    $script = (new FortrabbitScriptGenerator)->generate(fortrabbitPlan([
        'beforeDeploy' => [ProjectCommand::artisan('pennant:purge')],
        'beforeMigrations' => [ProjectCommand::artisan('wayfinder:generate')],
        'afterMigrations' => [ProjectCommand::artisan('model:typer')],
        'afterDeploy' => [ProjectCommand::artisan('cache:warm')],
    ]));

    expect($script)
        ->toContain('php artisan pennant:purge')
        ->toContain('php artisan wayfinder:generate')
        ->toContain('php artisan model:typer')
        ->toContain('php artisan cache:warm');

    // before-deploy runs before migrations; after-deploy runs after finalize.
    expect(strpos($script, 'pennant:purge'))->toBeLessThan(strpos($script, 'migrate --force'))
        ->and(strpos($script, 'cache:warm'))->toBeGreaterThan(strpos($script, 'storage:link'));
});

test('npm needs no global install line, non-npm managers do', function (): void {
    $npm = (new FortrabbitScriptGenerator)->generate(fortrabbitPlan(['packageManager' => PackageManager::NPM]));
    $bun = (new FortrabbitScriptGenerator)->generate(fortrabbitPlan(['packageManager' => PackageManager::BUN]));

    expect($npm)->not->toContain('npm i -g')
        ->and($bun)->toContain('npm i -g bun');
});

test('project commands wrap the migrate line in the post-deploy section', function (): void {
    $script = (new FortrabbitScriptGenerator)->generate(fortrabbitPlan([
        'beforeMigrations' => [ProjectCommand::artisan('wayfinder:generate', 'Generating routes...')],
        'afterMigrations' => [ProjectCommand::composer('dump-autoload --optimize')],
    ]));

    $before = strpos($script, 'php artisan wayfinder:generate');
    $migrate = strpos($script, 'php artisan migrate --force');
    $after = strpos($script, 'composer dump-autoload --optimize');

    expect($script)->toContain('# Generating routes...')
        ->and($before)->toBeLessThan($migrate)
        ->and($after)->toBeGreaterThan($migrate);
});

test('development drops no-dev and optimize; toggles drop their lines', function (): void {
    $script = (new FortrabbitScriptGenerator)->generate(fortrabbitPlan([
        'environment' => DeploymentEnvironment::DEVELOPMENT,
        'migrate' => false,
        'frontend' => false,
        'restartQueues' => false,
        'finalize' => [],
    ]));

    expect($script)->toContain('composer install --prefer-dist')
        ->and($script)->not->toContain('--no-dev')
        ->and($script)->not->toContain('artisan optimize')
        ->and($script)->not->toContain('migrate --force')
        ->and($script)->not->toContain('run build')
        ->and($script)->not->toContain('queue:restart')
        ->and($script)->not->toContain('storage:link');
});
