<?php

declare(strict_types=1);

use Igne\LaravelBootUp\Pipelines\PipelineEnvFile;

test('renders the committed sqlite test environment', function (): void {
    $content = (new PipelineEnvFile)->generate('base64:fixed-key-for-the-test');

    expect($content)->toBe(<<<'ENV'
# CI test environment — generated by igne-agency/laravel-boot-up.
# The pipeline copies this file over .env. Commit it; the APP_KEY is only ever used in CI.

APP_NAME=Laravel
APP_ENV=testing
APP_KEY=base64:fixed-key-for-the-test
APP_DEBUG=true
APP_URL=http://localhost

LOG_CHANNEL=stderr

DB_CONNECTION=sqlite
DB_DATABASE=:memory:

BROADCAST_CONNECTION=log
CACHE_STORE=array
SESSION_DRIVER=array
QUEUE_CONNECTION=sync
MAIL_MAILER=array

ENV);
});

test('generates a key:generate-formatted app key by default', function (): void {
    $content = (new PipelineEnvFile)->generate();

    expect($content)->toMatch('/^APP_KEY=base64:[A-Za-z0-9+\/]{43}=$/m');
});

test('random keys decode to 32 bytes and differ per call', function (): void {
    $key = PipelineEnvFile::randomKey();

    expect($key)->toStartWith('base64:')
        ->and(strlen((string) base64_decode(substr($key, 7), true)))->toBe(32)
        ->and(PipelineEnvFile::randomKey())->not->toBe($key);
});
