<?php

declare(strict_types=1);

namespace Igne\LaravelBootUp\Pipelines;

/**
 * Renders a Bitbucket Pipelines file: install & test on pull requests and on
 * pushes to the deploy branches, then curl the branch's deploy webhook.
 * Bitbucket runs each step's script fail-fast in a single bash session.
 */
final class BitbucketPipelinesGenerator implements PipelineGenerator
{
    public function __construct(private readonly PipelineSteps $steps) {}

    public function key(): string
    {
        return 'bitbucket';
    }

    public function label(): string
    {
        return 'Bitbucket Pipelines';
    }

    public function path(): string
    {
        return 'bitbucket-pipelines.yml';
    }

    public function generate(PipelinePlan $plan): string
    {
        $image = 'laravelsail/php'.str_replace('.', '', $plan->phpVersion).'-composer:latest';

        $lines = [
            '# CI/CD pipeline (Bitbucket Pipelines)',
            '# Generated by igne-agency/laravel-boot-up — lives at bitbucket-pipelines.yml.',
            "# Tests run on pull requests and on pushes to {$this->steps->branchList($plan)};",
            '# pushes then trigger the matching deploy webhook (skipped when its variable is unset).',
            '',
            "image: {$image}",
            '',
            'definitions:',
            '  steps:',
        ];

        $lint = $this->steps->lint($plan);

        if ($lint !== []) {
            $lines = [
                ...$lines,
                '    - step: &lint',
                '        name: Lint (Pint)',
                '        caches:',
                '          - composer',
                '        script:',
            ];

            foreach ($lint as $command) {
                $lines[] = '          - '.$this->scalar($command);
            }
        }

        $lines = [
            ...$lines,
            '    - step: &install-test',
            '        name: Install & test',
            '        caches:',
            '          - composer',
        ];

        if ($plan->deployment->frontend) {
            $lines[] = '          - node';
        }

        $lines[] = '        script:';

        foreach ($this->steps->installTest($plan) as $command) {
            $lines[] = '          - '.$this->scalar($command);
        }

        $lines = [
            ...$lines,
            '',
            'pipelines:',
            '  pull-requests:',
            "    '**':",
            ...$this->testSteps($lint !== []),
            '  branches:',
        ];

        foreach ($plan->branchHooks as $branch => $variable) {
            $lines[] = "    {$branch}:";
            $lines = [...$lines, ...$this->testSteps($lint !== [])];
            $lines[] = '      - step:';
            $lines[] = "          name: Deploy ({$branch})";
            $lines[] = '          script:';

            foreach ($this->steps->deployHook($variable, $variable, $branch) as $command) {
                $lines[] = '            - '.$this->scalar($command);
            }
        }

        return implode("\n", $lines)."\n";
    }

    public function instructions(PipelinePlan $plan): array
    {
        $lines = [
            'Commit bitbucket-pipelines.yml and .env.pipeline — the pipeline reads both.',
            'Enable Pipelines once under Repository settings → Pipelines → Settings.',
            'Create the variables listed above as secured repository variables (Repository settings → Repository variables).',
            "An unset deploy variable skips that branch's deploy with a notice instead of failing the run.",
        ];

        if ($plan->nova) {
            $lines[] = 'Composer reads COMPOSER_AUTH straight from the environment — no auth.json step is needed.';
        }

        $lines[] = 'Deploying from other branches (e.g. main)? Remap boot-up.pipeline.branches and regenerate.';

        return $lines;
    }

    /**
     * The step list every pipeline starts with: lint and install-test in
     * parallel (matching GitHub's independent jobs), or just install-test.
     *
     * @return list<string>
     */
    private function testSteps(bool $lint): array
    {
        if (! $lint) {
            return ['      - step: *install-test'];
        }

        return [
            '      - parallel:',
            '          - step: *lint',
            '          - step: *install-test',
        ];
    }

    /**
     * Single-quotes a command when it would not survive as a YAML plain
     * scalar. Normally a no-op: the shared steps avoid leading #, quotes,
     * flow indicators and ": " on purpose.
     */
    private function scalar(string $command): string
    {
        $unsafeFirst = $command === '' || str_contains('#&*!|>%@`"\'{}[],', $command[0]);
        $unsafeStart = str_starts_with($command, '- ') || str_starts_with($command, '? ') || str_starts_with($command, ': ');

        if (! $unsafeFirst && ! $unsafeStart && ! str_contains($command, ': ') && ! str_ends_with($command, ':')) {
            return $command;
        }

        return "'".str_replace("'", "''", $command)."'";
    }
}
