<?php

declare(strict_types=1);

namespace Igne\LaravelBootUp\Pipelines;

use Igne\LaravelBootUp\Support\Lines;

/**
 * Renders a Bitbucket Pipelines file: lint, build and test run as parallel
 * steps on pull requests and pushes; a green push then triggers the branch's
 * deployment-scoped deploy hook via scripts/ci/deploy-hook.sh.
 * All logic lives in the shared scripts — the pipeline only wires them up.
 */
final class BitbucketPipelinesGenerator implements PipelineGenerator
{
    public function __construct(private readonly CiScripts $scripts) {}

    public function key(): string
    {
        return 'bitbucket';
    }

    public function label(): string
    {
        return 'Bitbucket Pipelines';
    }

    public function files(PipelinePlan $plan): array
    {
        return [
            new GeneratedFile('bitbucket-pipelines.yml', $this->pipeline($plan)),
            ...$this->scripts->files($plan),
        ];
    }

    public function secrets(PipelinePlan $plan): array
    {
        $secrets = [];

        foreach ($plan->branchEnvironments as $branch => $environment) {
            $secrets[] = new PipelineSecret(
                'DEPLOY_HOOK',
                "Repository settings → Deployments → {$environment} → Variables (mark as secured; create the environment first)",
                "Deploy hook URL from your host — fortrabbit: dashboard → your app → {$environment} → Deploy hook",
                "Deploys {$environment} after a green push to {$branch}",
            );
        }

        if ($plan->nova) {
            $secrets[] = new PipelineSecret(
                'COMPOSER_AUTH',
                'Repository settings → Repository variables (mark as secured)',
                'Composer auth JSON for nova.laravel.com (example below)',
                'Lets composer install Laravel Nova in CI',
            );
        }

        return $secrets;
    }

    public function instructions(PipelinePlan $plan): array
    {
        $notes = [
            'Commit bitbucket-pipelines.yml, scripts/ci/* and .env.pipeline — every script also runs locally, e.g. `bash scripts/ci/test.sh`.',
            'Enable Pipelines once under Repository settings → Pipelines → Settings.',
            'DEPLOY_HOOK example (fortrabbit): https://api.fortrabbit.com/webhooks/environments/{app-env-id}/deploy/{secret}',
            'The deploy script always sends the `User-Agent: fortrabbit` header fortrabbit requires; other hosts ignore it.',
        ];

        if ($plan->nova) {
            $notes[] = 'COMPOSER_AUTH example: {"http-basic":{"nova.laravel.com":{"username":"you@example.com","password":"<license key>"}}}';
            $notes[] = 'Composer reads COMPOSER_AUTH straight from the environment — no auth.json step is needed.';
        }

        return [
            ...$notes,
            'Optional approval gate: add `trigger: manual` to the production deploy step.',
            "An unset DEPLOY_HOOK skips that environment's deploy with a notice instead of failing the run.",
            'Deploying from other branches (e.g. main)? Remap boot-up.pipeline.branches and regenerate.',
        ];
    }

    private function pipeline(PipelinePlan $plan): string
    {
        $image = 'laravelsail/php'.str_replace('.', '', $plan->phpVersion).'-composer:latest';

        return Lines::make()
            ->comment(
                'CI/CD pipeline (Bitbucket Pipelines)',
                'Generated by igne-agency/laravel-boot-up — lives at bitbucket-pipelines.yml.',
                "Checks run on pull requests and on pushes to {$this->scripts->branchList($plan)};",
                "a green push then triggers its environment's deploy hook via",
                'scripts/ci/deploy-hook.sh (skipped when DEPLOY_HOOK is unset).',
            )
            ->lineWithBreak("image: {$image}")
            ->lineWithBreak('definitions:')
            ->indent(2, fn (Lines $yaml) => $yaml
                ->line('steps:')
                ->indent(2, function (Lines $yaml) use ($plan): void {
                    if ($plan->pint) {
                        $this->stepDefinition($yaml, $plan, 'lint', 'Lint', node: false);
                    }

                    $this->stepDefinition($yaml, $plan, 'build', 'Build', node: true);
                    $this->stepDefinition($yaml, $plan, 'test', 'Test', node: true);
                }))
            ->lineWithBreak('pipelines:')
            ->indent(2, function (Lines $yaml) use ($plan): void {
                $yaml->line('pull-requests:')
                    ->indent(2, fn (Lines $yaml) => $yaml
                        ->line("'**':")
                        ->indent(2, fn (Lines $yaml) => $this->checkSteps($yaml, $plan)));

                $yaml->line('branches:')
                    ->indent(2, fn (Lines $yaml) => $yaml->each(
                        $plan->branchEnvironments,
                        function (Lines $yaml, string $environment, string $branch) use ($plan): void {
                            $yaml->line("{$branch}:")
                                ->indent(2, function (Lines $yaml) use ($plan, $environment): void {
                                    $this->checkSteps($yaml, $plan);
                                    $this->deployStep($yaml, $environment);
                                });
                        },
                    ));
            })
            ->render();
    }

    /**
     * One reusable step anchor calling its shared script. The node cache only
     * helps steps that install Node dependencies via bootstrap.sh.
     */
    private function stepDefinition(Lines $yaml, PipelinePlan $plan, string $step, string $name, bool $node): void
    {
        $yaml->line("- step: &{$step}")
            ->indent(4, fn (Lines $yaml) => $yaml
                ->line("name: {$name}")
                ->line('caches:')
                ->indent(2, fn (Lines $yaml) => $yaml
                    ->line('- composer')
                    ->when($node && $plan->deployment->frontend, fn (Lines $yaml) => $yaml->line('- node')))
                ->line('script:')
                ->indent(2, fn (Lines $yaml) => $yaml->line('- '.$this->scalar("bash scripts/ci/{$step}.sh"))));
    }

    /**
     * The parallel status checks every pipeline starts with, mirroring
     * GitHub's independent jobs.
     */
    private function checkSteps(Lines $yaml, PipelinePlan $plan): void
    {
        $yaml->line('- parallel:')
            ->indent(4, fn (Lines $yaml) => $yaml
                ->when($plan->pint, fn (Lines $yaml) => $yaml->line('- step: *lint'))
                ->line('- step: *build')
                ->line('- step: *test'));
    }

    /**
     * A deployment-tracked step: Bitbucket scopes the DEPLOY_HOOK variable to
     * the named environment and serializes deployments to it natively.
     */
    private function deployStep(Lines $yaml, string $environment): void
    {
        $yaml->line('- step:')
            ->indent(4, fn (Lines $yaml) => $yaml
                ->line("name: Deploy ({$environment})")
                ->line("deployment: {$environment}")
                ->line('script:')
                ->indent(2, fn (Lines $yaml) => $yaml
                    ->line('- '.$this->scalar("bash scripts/ci/deploy-hook.sh {$environment} \"\${DEPLOY_HOOK:-}\""))));
    }

    /**
     * Single-quotes a command when it would not survive as a YAML plain
     * scalar. Normally a no-op: the script invocations avoid leading #,
     * quotes, flow indicators and ": " on purpose.
     */
    private function scalar(string $command): string
    {
        $unsafeFirst = $command === '' || str_contains('#&*!|>%@`"\'{}[],', $command[0]);
        $unsafeStart = str_starts_with($command, '- ') || str_starts_with($command, '? ') || str_starts_with($command, ': ');

        if (! $unsafeFirst && ! $unsafeStart && ! str_contains($command, ': ') && ! str_ends_with($command, ':')) {
            return $command;
        }

        return "'".str_replace("'", "''", $command)."'";
    }
}
