<?php

declare(strict_types=1);

namespace Igne\LaravelBootUp\Pipelines;

use Igne\LaravelBootUp\Support\Lines;

/**
 * Renders a GitHub Actions workflow: lint, build and test run as parallel
 * status checks on pull requests and pushes; a green push then triggers the
 * branch's environment-scoped deploy hook via scripts/ci/deploy-hook.sh —
 * unless the plan's host is NONE, in which case the deploy jobs are omitted.
 * All logic lives in the shared scripts — the workflow only wires them up.
 */
final class GitHubActionsGenerator implements PipelineGenerator
{
    public function __construct(private readonly CiScripts $scripts) {}

    public function key(): string
    {
        return 'github';
    }

    public function label(): string
    {
        return 'GitHub Actions';
    }

    public function anchors(PipelinePlan $plan): array
    {
        return array_values(array_filter([
            $plan->pint ? 'lint' : null,
            'build',
            'test',
            $plan->host->deploys() ? 'deploy' : null,
        ]));
    }

    public function files(PipelinePlan $plan): array
    {
        return [
            new GeneratedFile('.github/workflows/ci.yml', $this->workflow($plan)),
            ...$this->scripts->files($plan),
        ];
    }

    public function secrets(PipelinePlan $plan): array
    {
        $secrets = [];

        if ($plan->host->deploys()) {
            $secrets[] = new PipelineSecret(
                'DEPLOY_HOOK',
                'each environment',
                'triggers the deploy on a green push',
                $this->deployHookDetails($plan),
            );
        }

        if ($plan->composerAuth) {
            $secrets[] = new PipelineSecret(
                'COMPOSER_AUTH',
                'repository secrets',
                'authenticates Composer for private/licensed packages',
                [
                    'Add under, in your GitHub repository: Settings → Secrets and variables → Actions → Repository secrets.',
                    'Value: composer auth JSON for the private registry your packages need — e.g. Laravel Nova:',
                    '{"http-basic":{"nova.laravel.com":{"username":"you@example.com","password":"<license key>"}}}',
                ],
            );
        }

        return $secrets;
    }

    public function notes(PipelinePlan $plan): array
    {
        $checks = $plan->pint ? 'Lint, Build and Test' : 'Build and Test';

        return [
            "Branch protection: require the {$checks} checks.",
            ...$plan->host->notes(),
            ...$plan->host->deploys() ? [
                "An unset DEPLOY_HOOK skips that environment's deploy with a notice instead of failing the run.",
                'Deploying from other branches? Remap boot-up.pipeline.branches and regenerate.',
            ] : [],
        ];
    }

    public function instructions(PipelinePlan $plan): array
    {
        return [
            'Commit .github/workflows/ci.yml, scripts/ci/* and .env.pipeline — every script also runs locally, e.g. `bash scripts/ci/test.sh`.',
            ...$this->secrets($plan) === [] ? [] : [
                'Add the secrets above to your GitHub repository (repository/environment secrets — each secret\'s section lists the exact path).',
            ],
            ...$plan->host->deploys() ? [] : [
                'Ready to deploy from this pipeline later? Rerun generate:pipeline with a deploy-hook host to add the deploy jobs.',
            ],
            ...$plan->pint ? ['Lint before every commit: run `php artisan generate:git-hooks` to install the pre-commit Pint hook.'] : [],
        ];
    }

    /**
     * One DEPLOY_HOOK entry covering every environment: a "set one per
     * environment" instruction, the generic settings path, then the host's
     * value guidance labelled per environment (the URL differs per env).
     *
     * @return list<string>
     */
    private function deployHookDetails(PipelinePlan $plan): array
    {
        $environments = array_values($plan->branchEnvironments);

        $details = [
            'Configure a DEPLOY_HOOK for EACH environment: '.implode(', ', $environments).'.',
            'Add under, in your GitHub repository: Settings → Environments → <environment> → Environment secrets (create each environment first).',
        ];

        foreach ($plan->branchEnvironments as $branch => $environment) {
            $details[] = "{$environment} (deploys on push to {$branch}):";

            foreach ($plan->host->hookValueGuidance($environment) as $line) {
                $details[] = '  '.$line;
            }
        }

        return $details;
    }

    private function workflow(PipelinePlan $plan): string
    {
        return Lines::make()
            ->comment(
                'CI/CD pipeline (GitHub Actions)',
                'Generated by igne-agency/laravel-boot-up — lives at .github/workflows/ci.yml.',
                ...$plan->host->deploys() ? [
                    "Checks run on pull requests and on pushes to {$this->scripts->branchList($plan)};",
                    "a green push then triggers its environment's deploy hook via",
                    'scripts/ci/deploy-hook.sh (skipped when DEPLOY_HOOK is unset).',
                ] : [
                    "Checks run on pull requests and on pushes to {$this->scripts->branchList($plan)}.",
                    'No deploy jobs were generated — rerun generate:pipeline with a deploy-hook host to add them.',
                ],
            )
            ->lineWithBreak('name: CI/CD')
            ->lineWithBreak('on:')
            ->indent(2, fn (Lines $yaml) => $yaml
                ->line('push:')
                ->indent(2, fn (Lines $yaml) => $yaml
                    ->line('branches: ['.implode(', ', array_keys($plan->branchEnvironments)).']'))
                ->line('pull_request:'))
            ->lineWithBreak('permissions:')
            ->indent(2, fn (Lines $yaml) => $yaml->line('contents: read'))
            ->blank()
            ->comment('Superseded pull-request runs are cancelled; push runs never are'.($plan->host->deploys() ? ' — they deploy.' : '.'))
            ->line('concurrency:')
            ->indent(2, fn (Lines $yaml) => $yaml
                ->line('group: ${{ github.workflow }}-${{ github.ref }}')
                ->line("cancel-in-progress: \${{ github.event_name == 'pull_request' }}"))
            ->lineWithBreak('jobs:')
            ->indent(2, function (Lines $yaml) use ($plan): void {
                $this->checkJobs($yaml, $plan);
                $this->deployJobs($yaml, $plan);
            })
            ->render();
    }

    /**
     * The lint/build/test status checks — independent parallel jobs so the
     * failure category is visible at a glance on the pull request.
     */
    private function checkJobs(Lines $yaml, PipelinePlan $plan): void
    {
        if ($plan->pint) {
            $this->checkJob($yaml, $plan, 'lint', 'Lint', 'Check the code style', 10);
        }

        $this->checkJob($yaml, $plan, 'build', 'Build', 'Build the frontend and framework caches', 15);
        $this->checkJob($yaml, $plan, 'test', 'Test', 'Run the test suite', 20);
    }

    private function checkJob(Lines $yaml, PipelinePlan $plan, string $job, string $name, string $step, int $timeout): void
    {
        $yaml->line("{$job}:")
            ->indent(2, function (Lines $yaml) use ($plan, $job, $name, $step, $timeout): void {
                $yaml->line("name: {$name}")
                    ->line('runs-on: ubuntu-latest')
                    ->line("timeout-minutes: {$timeout}")
                    ->line('steps:')
                    ->indent(2, function (Lines $yaml) use ($plan, $job, $step): void {
                        $this->setupSteps($yaml, $plan);

                        $this->extraSteps($yaml, $plan, $job, 'before');

                        $yaml->lineWithBreak("- name: {$step}")
                            ->indent(2, function (Lines $yaml) use ($plan, $job): void {
                                $this->composerAuth($yaml, $plan);
                                $yaml->line("run: bash scripts/ci/{$job}.sh");
                            });

                        $this->extraSteps($yaml, $plan, $job, 'after');
                    });
            })
            ->blank();
    }

    /**
     * One deploy job per branch → environment mapping. The environment scopes
     * the DEPLOY_HOOK secret and can carry approval rules; the concurrency
     * group queues deploys without ever cancelling one mid-flight.
     */
    private function deployJobs(Lines $yaml, PipelinePlan $plan): void
    {
        if (! $plan->host->deploys()) {
            return;
        }

        $needs = $plan->pint ? '[lint, build, test]' : '[build, test]';

        foreach ($plan->branchEnvironments as $branch => $environment) {
            $yaml->line("deploy-{$environment}:")
                ->indent(2, fn (Lines $yaml) => $yaml
                    ->line("name: Deploy ({$environment})")
                    ->line("needs: {$needs}")
                    ->line("if: github.event_name == 'push' && github.ref == 'refs/heads/{$branch}'")
                    ->line('runs-on: ubuntu-latest')
                    ->line('timeout-minutes: 5')
                    ->line("environment: {$environment}")
                    ->line('concurrency:')
                    ->indent(2, fn (Lines $yaml) => $yaml
                        ->line("group: deployment-{$environment}")
                        ->line('cancel-in-progress: false'))
                    ->line('steps:')
                    ->indent(2, function (Lines $yaml) use ($plan, $environment): void {
                        $yaml->line('- uses: actions/checkout@v5')
                            ->indent(2, fn (Lines $yaml) => $yaml
                                ->line('with:')
                                ->indent(2, fn (Lines $yaml) => $yaml->line('sparse-checkout: scripts/ci')));

                        $this->extraSteps($yaml, $plan, 'deploy', 'before');

                        $yaml->lineWithBreak("- name: Trigger the {$environment} deploy hook")
                            ->indent(2, fn (Lines $yaml) => $yaml
                                ->line('env:')
                                ->indent(2, fn (Lines $yaml) => $yaml->line('DEPLOY_HOOK: ${{ secrets.DEPLOY_HOOK }}'))
                                ->line("run: bash scripts/ci/deploy-hook.sh {$environment} \"\${DEPLOY_HOOK:-}\""));

                        $this->extraSteps($yaml, $plan, 'deploy', 'after');
                    }))
                ->blank();
        }
    }

    /**
     * The checkout → PHP → composer-cache preamble shared by every check job.
     */
    private function setupSteps(Lines $yaml, PipelinePlan $plan): void
    {
        $yaml->line('- uses: actions/checkout@v5')
            ->lineWithBreak('- name: Set up PHP')
            ->indent(2, fn (Lines $yaml) => $yaml
                ->line('uses: shivammathur/setup-php@v2')
                ->line('with:')
                ->indent(2, fn (Lines $yaml) => $yaml
                    ->line("php-version: '{$plan->phpVersion}'")
                    ->line('extensions: mbstring, dom, fileinfo, sqlite3, pdo_sqlite')
                    ->line('coverage: none')))
            ->lineWithBreak('- name: Determine the composer cache directory')
            ->indent(2, fn (Lines $yaml) => $yaml
                ->line('id: composer-cache')
                ->line('run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"'))
            ->lineWithBreak('- name: Cache composer dependencies')
            ->indent(2, fn (Lines $yaml) => $yaml
                ->line('uses: actions/cache@v5')
                ->line('with:')
                ->indent(2, fn (Lines $yaml) => $yaml
                    ->line('path: ${{ steps.composer-cache.outputs.dir }}')
                    ->line("key: composer-\${{ hashFiles('composer.lock') }}")
                    ->line('restore-keys: composer-')));
    }

    /**
     * Render the project's configured extra steps at one job anchor as GitHub
     * job steps, with their optional env block.
     */
    private function extraSteps(Lines $yaml, PipelinePlan $plan, string $job, string $position): void
    {
        foreach ($plan->extensions->stepsFor($this->key(), $job, $position) as $step) {
            $yaml->lineWithBreak("- name: {$step->name}")
                ->indent(2, function (Lines $yaml) use ($step): void {
                    if ($step->env !== []) {
                        $yaml->line('env:')
                            ->indent(2, fn (Lines $yaml) => $yaml->each(
                                $step->env,
                                fn (Lines $yaml, string $value, string $key) => $yaml->line("{$key}: {$value}"),
                            ));
                    }

                    $yaml->line("run: {$step->run}");
                });
        }
    }

    private function composerAuth(Lines $yaml, PipelinePlan $plan): void
    {
        if (! $plan->composerAuth) {
            return;
        }

        $yaml->line('env:')
            ->indent(2, fn (Lines $yaml) => $yaml->line('COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}'));
    }
}
