<?php

declare(strict_types=1);

namespace Igne\LaravelBootUp\Pipelines;

use Igne\LaravelBootUp\Support\Lines;

/**
 * Renders a GitHub Actions workflow: lint, build and test run as parallel
 * status checks on pull requests and pushes; a green push then triggers the
 * branch's environment-scoped deploy hook via scripts/ci/deploy-hook.sh.
 * All logic lives in the shared scripts — the workflow only wires them up.
 */
final class GitHubActionsGenerator implements PipelineGenerator
{
    public function __construct(private readonly CiScripts $scripts) {}

    public function key(): string
    {
        return 'github';
    }

    public function label(): string
    {
        return 'GitHub Actions';
    }

    public function files(PipelinePlan $plan): array
    {
        return [
            new GeneratedFile('.github/workflows/ci.yml', $this->workflow($plan)),
            ...$this->scripts->files($plan),
        ];
    }

    public function secrets(PipelinePlan $plan): array
    {
        $secrets = [];

        foreach ($plan->branchEnvironments as $branch => $environment) {
            $secrets[] = new PipelineSecret(
                'DEPLOY_HOOK',
                "Settings → Environments → {$environment} → Environment secrets (create the environment first)",
                "Deploy hook URL from your host — fortrabbit: dashboard → your app → {$environment} → Deploy hook",
                "Deploys {$environment} after a green push to {$branch}",
            );
        }

        if ($plan->nova) {
            $secrets[] = new PipelineSecret(
                'COMPOSER_AUTH',
                'Settings → Secrets and variables → Actions → Repository secrets',
                'Composer auth JSON for nova.laravel.com (example below)',
                'Lets composer install Laravel Nova in CI',
            );
        }

        return $secrets;
    }

    public function instructions(PipelinePlan $plan): array
    {
        $checks = $plan->pint ? 'Lint, Build and Test' : 'Build and Test';

        $notes = [
            'Commit .github/workflows/ci.yml, scripts/ci/* and .env.pipeline — every script also runs locally, e.g. `bash scripts/ci/test.sh`.',
            'DEPLOY_HOOK example (fortrabbit): https://api.fortrabbit.com/webhooks/environments/{app-env-id}/deploy/{secret}',
            'The deploy script always sends the `User-Agent: fortrabbit` header fortrabbit requires; other hosts ignore it.',
        ];

        if ($plan->nova) {
            $notes[] = 'COMPOSER_AUTH example: {"http-basic":{"nova.laravel.com":{"username":"you@example.com","password":"<license key>"}}}';
        }

        return [
            ...$notes,
            "Branch protection: require the {$checks} checks.",
            'Optional approval gate: add required reviewers to the production environment (Settings → Environments).',
            "An unset DEPLOY_HOOK skips that environment's deploy with a notice instead of failing the run.",
            'Deploying from other branches (e.g. main)? Remap boot-up.pipeline.branches and regenerate.',
        ];
    }

    private function workflow(PipelinePlan $plan): string
    {
        return Lines::make()
            ->comment(
                'CI/CD pipeline (GitHub Actions)',
                'Generated by igne-agency/laravel-boot-up — lives at .github/workflows/ci.yml.',
                "Checks run on pull requests and on pushes to {$this->scripts->branchList($plan)};",
                "a green push then triggers its environment's deploy hook via",
                'scripts/ci/deploy-hook.sh (skipped when DEPLOY_HOOK is unset).',
            )
            ->lineWithBreak('name: CI/CD')
            ->lineWithBreak('on:')
            ->indent(2, fn (Lines $yaml) => $yaml
                ->line('push:')
                ->indent(2, fn (Lines $yaml) => $yaml
                    ->line('branches: ['.implode(', ', array_keys($plan->branchEnvironments)).']'))
                ->line('pull_request:'))
            ->lineWithBreak('permissions:')
            ->indent(2, fn (Lines $yaml) => $yaml->line('contents: read'))
            ->blank()
            ->comment('Superseded pull-request runs are cancelled; push runs never are — they deploy.')
            ->line('concurrency:')
            ->indent(2, fn (Lines $yaml) => $yaml
                ->line('group: ${{ github.workflow }}-${{ github.ref }}')
                ->line("cancel-in-progress: \${{ github.event_name == 'pull_request' }}"))
            ->lineWithBreak('jobs:')
            ->indent(2, function (Lines $yaml) use ($plan): void {
                $this->checkJobs($yaml, $plan);
                $this->deployJobs($yaml, $plan);
            })
            ->render();
    }

    /**
     * The lint/build/test status checks — independent parallel jobs so the
     * failure category is visible at a glance on the pull request.
     */
    private function checkJobs(Lines $yaml, PipelinePlan $plan): void
    {
        if ($plan->pint) {
            $this->checkJob($yaml, $plan, 'lint', 'Lint', 'Check the code style', 10);
        }

        $this->checkJob($yaml, $plan, 'build', 'Build', 'Build the frontend and framework caches', 15);
        $this->checkJob($yaml, $plan, 'test', 'Test', 'Run the test suite', 20);
    }

    private function checkJob(Lines $yaml, PipelinePlan $plan, string $job, string $name, string $step, int $timeout): void
    {
        $yaml->line("{$job}:")
            ->indent(2, function (Lines $yaml) use ($plan, $job, $name, $step, $timeout): void {
                $yaml->line("name: {$name}")
                    ->line('runs-on: ubuntu-latest')
                    ->line("timeout-minutes: {$timeout}")
                    ->line('steps:')
                    ->indent(2, function (Lines $yaml) use ($plan, $job, $step): void {
                        $this->setupSteps($yaml, $plan);

                        $yaml->lineWithBreak("- name: {$step}")
                            ->indent(2, function (Lines $yaml) use ($plan, $job): void {
                                $this->composerAuth($yaml, $plan);
                                $yaml->line("run: bash scripts/ci/{$job}.sh");
                            });
                    });
            })
            ->blank();
    }

    /**
     * One deploy job per branch → environment mapping. The environment scopes
     * the DEPLOY_HOOK secret and can carry approval rules; the concurrency
     * group queues deploys without ever cancelling one mid-flight.
     */
    private function deployJobs(Lines $yaml, PipelinePlan $plan): void
    {
        $needs = $plan->pint ? '[lint, build, test]' : '[build, test]';

        foreach ($plan->branchEnvironments as $branch => $environment) {
            $yaml->line("deploy-{$environment}:")
                ->indent(2, fn (Lines $yaml) => $yaml
                    ->line("name: Deploy ({$environment})")
                    ->line("needs: {$needs}")
                    ->line("if: github.event_name == 'push' && github.ref == 'refs/heads/{$branch}'")
                    ->line('runs-on: ubuntu-latest')
                    ->line('timeout-minutes: 5')
                    ->line("environment: {$environment}")
                    ->line('concurrency:')
                    ->indent(2, fn (Lines $yaml) => $yaml
                        ->line("group: deployment-{$environment}")
                        ->line('cancel-in-progress: false'))
                    ->line('steps:')
                    ->indent(2, fn (Lines $yaml) => $yaml
                        ->line('- uses: actions/checkout@v5')
                        ->indent(2, fn (Lines $yaml) => $yaml
                            ->line('with:')
                            ->indent(2, fn (Lines $yaml) => $yaml->line('sparse-checkout: scripts/ci')))
                        ->lineWithBreak("- name: Trigger the {$environment} deploy hook")
                        ->indent(2, fn (Lines $yaml) => $yaml
                            ->line('env:')
                            ->indent(2, fn (Lines $yaml) => $yaml->line('DEPLOY_HOOK: ${{ secrets.DEPLOY_HOOK }}'))
                            ->line("run: bash scripts/ci/deploy-hook.sh {$environment} \"\${DEPLOY_HOOK:-}\""))))
                ->blank();
        }
    }

    /**
     * The checkout → PHP → composer-cache preamble shared by every check job.
     */
    private function setupSteps(Lines $yaml, PipelinePlan $plan): void
    {
        $yaml->line('- uses: actions/checkout@v5')
            ->lineWithBreak('- name: Set up PHP')
            ->indent(2, fn (Lines $yaml) => $yaml
                ->line('uses: shivammathur/setup-php@v2')
                ->line('with:')
                ->indent(2, fn (Lines $yaml) => $yaml
                    ->line("php-version: '{$plan->phpVersion}'")
                    ->line('extensions: mbstring, dom, fileinfo, sqlite3, pdo_sqlite')
                    ->line('coverage: none')))
            ->lineWithBreak('- name: Determine the composer cache directory')
            ->indent(2, fn (Lines $yaml) => $yaml
                ->line('id: composer-cache')
                ->line('run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"'))
            ->lineWithBreak('- name: Cache composer dependencies')
            ->indent(2, fn (Lines $yaml) => $yaml
                ->line('uses: actions/cache@v5')
                ->line('with:')
                ->indent(2, fn (Lines $yaml) => $yaml
                    ->line('path: ${{ steps.composer-cache.outputs.dir }}')
                    ->line("key: composer-\${{ hashFiles('composer.lock') }}")
                    ->line('restore-keys: composer-')));
    }

    private function composerAuth(Lines $yaml, PipelinePlan $plan): void
    {
        if (! $plan->nova) {
            return;
        }

        $yaml->line('env:')
            ->indent(2, fn (Lines $yaml) => $yaml->line('COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}'));
    }
}
