<?php

declare(strict_types=1);

namespace Igne\LaravelBootUp\Pipelines;

/**
 * Renders a GitHub Actions workflow: install & test on pull requests and on
 * pushes to the deploy branches, then curl the branch's deploy webhook.
 * GitHub runs `run` blocks with `bash -e`, so every command is fail-fast.
 */
final class GitHubActionsGenerator implements PipelineGenerator
{
    public function __construct(private readonly PipelineSteps $steps) {}

    public function key(): string
    {
        return 'github';
    }

    public function label(): string
    {
        return 'GitHub Actions';
    }

    public function path(): string
    {
        return '.github/workflows/ci.yml';
    }

    public function generate(PipelinePlan $plan): string
    {
        $lines = [
            '# CI/CD pipeline (GitHub Actions)',
            '# Generated by igne-agency/laravel-boot-up — lives at .github/workflows/ci.yml.',
            "# Tests run on pull requests and on pushes to {$this->steps->branchList($plan)};",
            '# pushes then trigger the matching deploy webhook (skipped when its secret is unset).',
            '',
            'name: CI',
            '',
            'on:',
            '  push:',
            '    branches: ['.implode(', ', array_keys($plan->branchHooks)).']',
            '  pull_request:',
            '',
            'concurrency:',
            '  group: ${{ github.workflow }}-${{ github.ref }}',
            '  cancel-in-progress: true',
            '',
            'jobs:',
            ...$this->lintJob($plan),
            ...$this->installTestJob($plan),
            '',
            ...$this->deployJob($plan),
        ];

        return implode("\n", $lines)."\n";
    }

    public function instructions(PipelinePlan $plan): array
    {
        return [
            'Commit .github/workflows/ci.yml and .env.pipeline — the workflow reads both.',
            'Create the secrets listed above under GitHub → Settings → Secrets and variables → Actions.',
            "An unset deploy secret skips that branch's deploy with a notice instead of failing the run.",
            'A new push to the same branch cancels the run already in progress.',
            'Deploying from other branches (e.g. main)? Remap boot-up.pipeline.branches and regenerate.',
        ];
    }

    /**
     * The checkout → PHP → composer-cache preamble shared by the lint and
     * install-test jobs.
     *
     * @return list<string>
     */
    private function setupSteps(PipelinePlan $plan): array
    {
        return [
            '      - uses: actions/checkout@v5',
            '',
            '      - name: Set up PHP',
            '        uses: shivammathur/setup-php@v2',
            '        with:',
            "          php-version: '{$plan->phpVersion}'",
            '          extensions: mbstring, dom, fileinfo, sqlite3, pdo_sqlite',
            '          coverage: none',
            '',
            '      - name: Determine the composer cache directory',
            '        id: composer-cache',
            '        run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"',
            '',
            '      - name: Cache composer dependencies',
            '        uses: actions/cache@v5',
            '        with:',
            '          path: ${{ steps.composer-cache.outputs.dir }}',
            "          key: composer-\${{ hashFiles('composer.lock') }}",
            '          restore-keys: composer-',
        ];
    }

    /**
     * @return list<string>
     */
    private function composerAuth(PipelinePlan $plan): array
    {
        if (! $plan->nova) {
            return [];
        }

        return [
            '        env:',
            '          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}',
        ];
    }

    /**
     * @return list<string>
     */
    private function lintJob(PipelinePlan $plan): array
    {
        $lint = $this->steps->lint($plan);

        if ($lint === []) {
            return [];
        }

        return [
            '  lint:',
            '    name: Lint (Pint)',
            '    runs-on: ubuntu-latest',
            '    steps:',
            ...$this->setupSteps($plan),
            '',
            '      - name: Check code style',
            ...$this->composerAuth($plan),
            ...$this->run($lint),
            '',
        ];
    }

    /**
     * @return list<string>
     */
    private function installTestJob(PipelinePlan $plan): array
    {
        $lines = [
            '  install-test:',
            '    name: Install & test',
            '    runs-on: ubuntu-latest',
            '    steps:',
            ...$this->setupSteps($plan),
            '',
            '      - name: Install composer dependencies',
            ...$this->composerAuth($plan),
        ];

        $lines = [
            ...$lines,
            ...$this->run($this->steps->composerInstall()),
            '',
            '      - name: Prepare the test environment',
            ...$this->run($this->steps->prepareEnvironment($plan)),
        ];

        if ($plan->nova) {
            $lines = [
                ...$lines,
                '',
                '      - name: Publish Nova assets',
                ...$this->run($this->steps->novaPublish($plan)),
            ];
        }

        if ($plan->deployment->frontend) {
            $lines = [
                ...$lines,
                '',
                '      - name: Build frontend assets',
                ...$this->run($this->steps->frontend($plan)),
            ];
        }

        return [
            ...$lines,
            '',
            '      - name: Run the test suite',
            ...$this->run($this->steps->testSuite($plan)),
        ];
    }

    /**
     * @return list<string>
     */
    private function deployJob(PipelinePlan $plan): array
    {
        $needs = $this->steps->lint($plan) === [] ? 'install-test' : '[lint, install-test]';

        $lines = [
            '  deploy:',
            '    name: Deploy',
            "    needs: {$needs}",
            "    if: github.event_name == 'push'",
            '    runs-on: ubuntu-latest',
            '    steps:',
            '      - name: Trigger the deploy webhook',
            '        env:',
        ];

        foreach (array_unique($plan->branchHooks) as $secret) {
            $lines[] = "          {$secret}: \${{ secrets.{$secret} }}";
        }

        $script = ['case "$GITHUB_REF_NAME" in'];

        foreach ($plan->branchHooks as $branch => $secret) {
            $script[] = "  {$branch}) hook=\"\${$secret}\"; secret=\"{$secret}\" ;;";
        }

        $script[] = '  *) echo "Branch $GITHUB_REF_NAME does not deploy — skipping."; exit 0 ;;';
        $script[] = 'esac';

        return [
            ...$lines,
            ...$this->run([...$script, ...$this->steps->deployHook('hook', '$secret', '$GITHUB_REF_NAME')]),
        ];
    }

    /**
     * A `run:` line for a single command, or a `run: |` block for several.
     *
     * @param  list<string>  $commands
     * @return list<string>
     */
    private function run(array $commands): array
    {
        if (\count($commands) === 1) {
            return ["        run: {$commands[0]}"];
        }

        return [
            '        run: |',
            ...array_map(static fn (string $command): string => "          {$command}", $commands),
        ];
    }
}
