<?php

declare(strict_types=1);

namespace Igne\LaravelBootstrap\Pipelines;

/**
 * Renders a fresh .env.pipeline: the committed CI test environment the
 * generated pipelines copy over .env. Deliberately not Environment\EnvFile,
 * which line-edits an existing file.
 */
final class PipelineEnvFile
{
    public function path(): string
    {
        return '.env.pipeline';
    }

    public function generate(?string $appKey = null): string
    {
        $lines = [
            '# CI test environment — generated by igne-agency/laravel-bootstrap.',
            '# The pipeline copies this file over .env. Commit it; the APP_KEY is only ever used in CI.',
            '',
            'APP_NAME=Laravel',
            'APP_ENV=testing',
            'APP_KEY='.($appKey ?? self::randomKey()),
            'APP_DEBUG=true',
            'APP_URL=http://localhost',
            '',
            'LOG_CHANNEL=stderr',
            '',
            'DB_CONNECTION=sqlite',
            'DB_DATABASE=:memory:',
            '',
            'BROADCAST_CONNECTION=log',
            'CACHE_STORE=array',
            'SESSION_DRIVER=array',
            'QUEUE_CONNECTION=sync',
            'MAIL_MAILER=array',
        ];

        return implode("\n", $lines)."\n";
    }

    /**
     * The exact format `php artisan key:generate` produces.
     */
    public static function randomKey(): string
    {
        return 'base64:'.base64_encode(random_bytes(32));
    }
}
