<?php

declare(strict_types=1);

namespace Igne\LaravelBootUp\Pipelines;

use Igne\LaravelBootUp\Data\Lines;

/**
 * Renders a fresh .env.pipeline: the committed CI test environment the
 * generated pipelines copy over .env. Deliberately not Environment\EnvFile,
 * which line-edits an existing file.
 */
final class PipelineEnvFile
{
    public function path(): string
    {
        return '.env.pipeline';
    }

    public function generate(?string $appKey = null): string
    {
        return Lines::make()
            ->comment(
                'CI test environment — generated by igne-agency/laravel-boot-up.',
                'The pipeline copies this file over .env. Commit it; the APP_KEY is only ever used in CI.',
            )
            ->lineWithBreak('APP_NAME=Laravel')
            ->line('APP_ENV=testing')
            ->line('APP_KEY='.($appKey ?? self::randomKey()))
            ->line('APP_DEBUG=true')
            ->line('APP_URL=http://localhost')
            ->lineWithBreak('LOG_CHANNEL=stderr')
            ->lineWithBreak('DB_CONNECTION=sqlite')
            ->line('DB_DATABASE=:memory:')
            ->lineWithBreak('BROADCAST_CONNECTION=log')
            ->line('CACHE_STORE=array')
            ->line('SESSION_DRIVER=array')
            ->line('QUEUE_CONNECTION=sync')
            ->line('MAIL_MAILER=array')
            ->render();
    }

    /**
     * The exact format `php artisan key:generate` produces.
     */
    public static function randomKey(): string
    {
        return 'base64:'.base64_encode(random_bytes(32));
    }

    /**
     * The APP_KEY found in existing .env.pipeline contents, or null when the
     * key is absent or present but empty — so callers can preserve a set key
     * across regeneration and only mint a fresh one when there isn't one.
     */
    public function currentAppKey(string $contents): ?string
    {
        if (preg_match('/^APP_KEY[ \t]*=[ \t]*(.*)$/m', $contents, $matches) !== 1) {
            return null;
        }

        $value = trim($matches[1]);

        return $value === '' ? null : $value;
    }
}
