<?php

declare(strict_types=1);

namespace Igne\LaravelBootUp\Pipelines;

use Igne\LaravelBootUp\Data\Lines;

/**
 * The header every generated bash script opens with: shebang, purpose,
 * provenance naming the exact regenerate command, strict mode.
 */
final class ScriptHeader
{
    public static function for(string $regenerateCommand, string $purpose, string ...$notes): Lines
    {
        return Lines::make()
            ->line('#!/usr/bin/env bash')
            ->comment('')
            ->comment($purpose)
            ->comment('')
            ->comment("Generated by igne-agency/laravel-boot-up — regenerate with `{$regenerateCommand}`.")
            ->comment(...$notes)
            ->lineWithBreak('set -euo pipefail');
    }
}
