<?php

declare(strict_types=1);

use Igne\LaravelBootUp\Deploy\Scripts\DeploymentEnvironment;
use Igne\LaravelBootUp\Deploy\Scripts\DeploymentPlan;
use Igne\LaravelBootUp\Frontend\PackageManager;
use Igne\LaravelBootUp\Pipelines\BitbucketPipelinesGenerator;
use Igne\LaravelBootUp\Pipelines\GitHubActionsGenerator;
use Igne\LaravelBootUp\Pipelines\PipelinePlan;
use Igne\LaravelBootUp\Pipelines\PipelineSteps;

function bitbucketPipelinePlan(array $overrides = [], array $deploymentOverrides = []): PipelinePlan
{
    $deploymentDefaults = [
        'environment' => DeploymentEnvironment::DEVELOPMENT,
        'migrate' => true,
        'finalize' => ['storage:link'],
        'beforeMigrations' => [],
        'afterMigrations' => [],
        'frontend' => true,
        'packageManager' => PackageManager::NPM,
        'restartQueues' => true,
    ];

    $defaults = [
        'deployment' => new DeploymentPlan(...array_merge($deploymentDefaults, $deploymentOverrides)),
        'nova' => true,
        'pint' => true,
        'phpVersion' => '8.4',
        'branchHooks' => [
            'develop' => 'DEV_DEPLOY',
            'staging' => 'STAGING_DEPLOY',
            'master' => 'PROD_DEPLOY',
        ],
    ];

    return new PipelinePlan(...array_merge($defaults, $overrides));
}

function bitbucketGenerator(): BitbucketPipelinesGenerator
{
    return new BitbucketPipelinesGenerator(new PipelineSteps);
}

test('renders the full pipeline for a nova project with a frontend', function (): void {
    $yaml = bitbucketGenerator()->generate(bitbucketPipelinePlan());

    expect($yaml)->toBe(<<<'YAML'
# CI/CD pipeline (Bitbucket Pipelines)
# Generated by igne-agency/laravel-boot-up — lives at bitbucket-pipelines.yml.
# Tests run on pull requests and on pushes to develop, staging and master;
# pushes then trigger the matching deploy webhook (skipped when its variable is unset).

image: laravelsail/php84-composer:latest

definitions:
  steps:
    - step: &lint
        name: Lint (Pint)
        caches:
          - composer
        script:
          - composer install --no-interaction --prefer-dist --no-progress --no-scripts
          - vendor/bin/pint --test
    - step: &install-test
        name: Install & test
        caches:
          - composer
          - node
        script:
          - composer install --no-interaction --prefer-dist --optimize-autoloader --no-progress
          - cp .env.pipeline .env
          - mkdir -p storage/framework/cache storage/framework/sessions storage/framework/testing storage/framework/views
          - php artisan nova:publish
          - npm ci || npm install
          - npm run build
          - php artisan config:clear
          - php artisan storage:link
          - php artisan migrate --force
          - php artisan test

pipelines:
  pull-requests:
    '**':
      - parallel:
          - step: *lint
          - step: *install-test
  branches:
    develop:
      - parallel:
          - step: *lint
          - step: *install-test
      - step:
          name: Deploy (develop)
          script:
            - if [ -z "$DEV_DEPLOY" ]; then echo "DEV_DEPLOY is not set — skipping deploy for develop."; exit 0; fi
            - curl --silent --show-error --fail-with-body -X POST "$DEV_DEPLOY"
    staging:
      - parallel:
          - step: *lint
          - step: *install-test
      - step:
          name: Deploy (staging)
          script:
            - if [ -z "$STAGING_DEPLOY" ]; then echo "STAGING_DEPLOY is not set — skipping deploy for staging."; exit 0; fi
            - curl --silent --show-error --fail-with-body -X POST "$STAGING_DEPLOY"
    master:
      - parallel:
          - step: *lint
          - step: *install-test
      - step:
          name: Deploy (master)
          script:
            - if [ -z "$PROD_DEPLOY" ]; then echo "PROD_DEPLOY is not set — skipping deploy for master."; exit 0; fi
            - curl --silent --show-error --fail-with-body -X POST "$PROD_DEPLOY"

YAML);
});

test('the image name is derived from the composer.json php version', function (): void {
    $yaml = bitbucketGenerator()->generate(bitbucketPipelinePlan(['phpVersion' => '8.3']));

    expect($yaml)->toContain('image: laravelsail/php83-composer:latest');
});

test('no database service is defined — tests run on sqlite', function (): void {
    $yaml = bitbucketGenerator()->generate(bitbucketPipelinePlan());

    expect($yaml)->not->toContain('services')
        ->and($yaml)->not->toContain('mysql');
});

test('the node cache is only defined for projects with a frontend', function (): void {
    $with = bitbucketGenerator()->generate(bitbucketPipelinePlan());
    $without = bitbucketGenerator()->generate(bitbucketPipelinePlan([], ['frontend' => false]));

    expect($with)->toContain('- node')
        ->and($without)->not->toContain('- node')
        ->and($without)->toContain('- composer');
});

test('a project without pint runs install-test alone, without a parallel block', function (): void {
    $yaml = bitbucketGenerator()->generate(bitbucketPipelinePlan(['pint' => false]));

    expect($yaml)->not->toContain('&lint')
        ->and($yaml)->not->toContain('pint --test')
        ->and($yaml)->not->toContain('parallel')
        ->and($yaml)->toContain('      - step: *install-test');
});

test('custom branch hooks drive the branch pipelines', function (): void {
    $yaml = bitbucketGenerator()->generate(bitbucketPipelinePlan([
        'branchHooks' => ['main' => 'PROD_DEPLOY'],
    ]));

    expect($yaml)->toContain('    main:')
        ->and($yaml)->toContain('Deploy (main)')
        ->and($yaml)->toContain('# Tests run on pull requests and on pushes to main;')
        ->and($yaml)->not->toContain('DEV_DEPLOY');
});

test('both providers run the identical install-test command sequence, in order', function (): void {
    $plan = bitbucketPipelinePlan();
    $steps = new PipelineSteps;

    $outputs = [
        'github' => (new GitHubActionsGenerator($steps))->generate($plan),
        'bitbucket' => (new BitbucketPipelinesGenerator($steps))->generate($plan),
    ];

    foreach ($outputs as $provider => $yaml) {
        foreach ([$steps->lint($plan), $steps->installTest($plan)] as $sequence) {
            $offset = 0;

            foreach ($sequence as $command) {
                $position = strpos($yaml, $command, $offset);

                expect($position)->not->toBeFalse("[{$provider}] is missing '{$command}' (in order)");

                $offset = (int) $position + strlen($command);
            }
        }
    }
});
