<?php

declare(strict_types=1);

use Igne\LaravelBootUp\Deploy\Scripts\DeploymentEnvironment;
use Igne\LaravelBootUp\Deploy\Scripts\DeploymentPlan;
use Igne\LaravelBootUp\Frontend\PackageManager;
use Igne\LaravelBootUp\Pipelines\BitbucketPipelinesGenerator;
use Igne\LaravelBootUp\Pipelines\CiScripts;
use Igne\LaravelBootUp\Pipelines\DeployHookHost;
use Igne\LaravelBootUp\Pipelines\GitHubActionsGenerator;
use Igne\LaravelBootUp\Pipelines\PipelinePlan;

function bitbucketPipelinePlan(array $overrides = [], array $deploymentOverrides = []): PipelinePlan
{
    $deploymentDefaults = [
        'environment' => DeploymentEnvironment::DEVELOPMENT,
        'migrate' => true,
        'finalize' => ['storage:link'],
        'beforeMigrations' => [],
        'afterMigrations' => [],
        'frontend' => true,
        'packageManager' => PackageManager::NPM,
        'restartQueues' => true,
    ];

    $defaults = [
        'deployment' => new DeploymentPlan(...array_merge($deploymentDefaults, $deploymentOverrides)),
        'nova' => true,
        'pint' => true,
        'phpVersion' => '8.4',
        'branchEnvironments' => [
            'develop' => 'development',
            'staging' => 'staging',
            'main' => 'production',
        ],
        'host' => DeployHookHost::FORTRABBIT,
    ];

    return new PipelinePlan(...array_merge($defaults, $overrides));
}

function bitbucketGenerator(): BitbucketPipelinesGenerator
{
    return new BitbucketPipelinesGenerator(new CiScripts);
}

function bitbucketPipeline(PipelinePlan $plan): string
{
    return bitbucketGenerator()->files($plan)[0]->contents;
}

test('renders the full pipeline for a nova project with pint', function (): void {
    $yaml = bitbucketPipeline(bitbucketPipelinePlan());

    expect($yaml)->toBe(<<<'YAML'
# CI/CD pipeline (Bitbucket Pipelines)
# Generated by igne-agency/laravel-boot-up — lives at bitbucket-pipelines.yml.
# Checks run on pull requests and on pushes to develop, staging and main;
# a green push then triggers its environment's deploy hook via
# scripts/ci/deploy-hook.sh (skipped when DEPLOY_HOOK is unset).

image: laravelsail/php84-composer:latest

definitions:
  steps:
    - step: &lint
        name: Lint
        caches:
          - composer
        script:
          - bash scripts/ci/lint.sh
    - step: &build
        name: Build
        caches:
          - composer
          - node
        script:
          - bash scripts/ci/build.sh
    - step: &test
        name: Test
        caches:
          - composer
          - node
        script:
          - bash scripts/ci/test.sh

pipelines:
  pull-requests:
    '**':
      - parallel:
          - step: *lint
          - step: *build
          - step: *test
  branches:
    develop:
      - parallel:
          - step: *lint
          - step: *build
          - step: *test
      - step:
          name: Deploy (development)
          deployment: development
          script:
            - bash scripts/ci/deploy-hook.sh development "${DEPLOY_HOOK:-}"
    staging:
      - parallel:
          - step: *lint
          - step: *build
          - step: *test
      - step:
          name: Deploy (staging)
          deployment: staging
          script:
            - bash scripts/ci/deploy-hook.sh staging "${DEPLOY_HOOK:-}"
    main:
      - parallel:
          - step: *lint
          - step: *build
          - step: *test
      - step:
          name: Deploy (production)
          deployment: production
          script:
            - bash scripts/ci/deploy-hook.sh production "${DEPLOY_HOOK:-}"

YAML);
});

test('files lists the pipeline first, then every shared script', function (): void {
    $paths = array_map(fn ($file) => $file->path, bitbucketGenerator()->files(bitbucketPipelinePlan()));

    expect($paths)->toBe([
        'bitbucket-pipelines.yml',
        'scripts/ci/bootstrap.sh',
        'scripts/ci/lint.sh',
        'scripts/ci/build.sh',
        'scripts/ci/test.sh',
        'scripts/ci/deploy-hook.sh',
    ]);
});

test('the image name is derived from the composer.json php version', function (): void {
    expect(bitbucketPipeline(bitbucketPipelinePlan(['phpVersion' => '8.3'])))
        ->toContain('image: laravelsail/php83-composer:latest');
});

test('no database service is defined — tests run on sqlite', function (): void {
    $yaml = bitbucketPipeline(bitbucketPipelinePlan());

    expect($yaml)->not->toContain('services')
        ->and($yaml)->not->toContain('mysql');
});

test('the node cache is only defined for projects with a frontend', function (): void {
    $with = bitbucketPipeline(bitbucketPipelinePlan());
    $without = bitbucketPipeline(bitbucketPipelinePlan([], ['frontend' => false]));

    expect($with)->toContain('- node')
        ->and($without)->not->toContain('- node')
        ->and($without)->toContain('- composer');
});

test('a project without pint runs build and test in parallel, without a lint step', function (): void {
    $yaml = bitbucketPipeline(bitbucketPipelinePlan(['pint' => false]));

    expect($yaml)->not->toContain('&lint')
        ->and($yaml)->not->toContain('*lint')
        ->and($yaml)->not->toContain('lint.sh')
        ->and($yaml)->toContain('- parallel:')
        ->and($yaml)->toContain('- step: *build')
        ->and($yaml)->toContain('- step: *test');
});

test('custom branches drive the branch pipelines and deployment environments', function (): void {
    $yaml = bitbucketPipeline(bitbucketPipelinePlan([
        'branchEnvironments' => ['main' => 'production'],
    ]));

    expect($yaml)->toContain('    main:')
        ->and($yaml)->toContain('Deploy (production)')
        ->and($yaml)->toContain('deployment: production')
        ->and($yaml)->toContain('# Checks run on pull requests and on pushes to main;')
        ->and($yaml)->not->toContain('deployment: development');
});

test('secrets list one deployment-scoped DEPLOY_HOOK per branch and COMPOSER_AUTH for nova', function (): void {
    $secrets = bitbucketGenerator()->secrets(bitbucketPipelinePlan());

    expect(array_map(fn ($secret) => $secret->name, $secrets))
        ->toBe(['DEPLOY_HOOK', 'DEPLOY_HOOK', 'DEPLOY_HOOK', 'COMPOSER_AUTH'])
        ->and($secrets[0]->location)->toBe('development deployment')
        ->and($secrets[0]->purpose)->toBe('deploys on push to develop')
        ->and(implode("\n", $secrets[0]->details))->toContain('Add under: Repository settings → Deployments → development → Variables')
        ->and(implode("\n", $secrets[0]->details))->toContain('https://api.fortrabbit.com/webhooks/environments/{app-env-id}/deploy/{secret}')
        ->and($secrets[3]->location)->toBe('repository variables')
        ->and(implode("\n", $secrets[3]->details))->toContain('Repository settings → Repository variables (mark as secured)')
        ->and(implode("\n", $secrets[3]->details))->toContain('Composer reads COMPOSER_AUTH straight from the environment');
});

function bitbucketGuidance(PipelinePlan $plan): string
{
    return implode("\n", [
        ...array_merge(...array_map(fn ($secret) => $secret->details, bitbucketGenerator()->secrets($plan))),
        ...bitbucketGenerator()->instructions($plan),
    ]);
}

test('the fortrabbit host gets the dashboard path, the hook example and the user-agent note', function (): void {
    $plan = bitbucketPipelinePlan(['host' => DeployHookHost::FORTRABBIT]);
    $guidance = bitbucketGuidance($plan);
    $instructions = implode("\n", bitbucketGenerator()->instructions($plan));

    expect($guidance)->toContain('fortrabbit dashboard')
        ->and($guidance)->toContain('https://api.fortrabbit.com/webhooks/environments/{app-env-id}/deploy/{secret}')
        ->and($instructions)->toContain('User-Agent: fortrabbit')
        ->and($instructions)->toContain('Enable Pipelines once')
        ->and($instructions)->toContain('trigger: manual');
});

test('the forge host gets the deployment trigger URL and no fortrabbit mentions', function (): void {
    $guidance = bitbucketGuidance(bitbucketPipelinePlan(['host' => DeployHookHost::FORGE]));

    expect($guidance)->toContain('Deployment trigger URL')
        ->and($guidance)->not->toContain('fortrabbit');
});

test('the webhook host gets neutral guidance naming no host', function (): void {
    $guidance = bitbucketGuidance(bitbucketPipelinePlan(['host' => DeployHookHost::WEBHOOK]));

    expect($guidance)->toContain("your host's HTTPS deploy hook URL for development")
        ->and($guidance)->not->toContain('fortrabbit')
        ->and($guidance)->not->toContain('Forge');
});

test('the none host renders a checks-only pipeline that still runs on branch pushes', function (): void {
    $yaml = bitbucketPipeline(bitbucketPipelinePlan(['host' => DeployHookHost::NONE]));

    expect($yaml)->toContain('# Checks run on pull requests and on pushes to develop, staging and main.')
        ->and($yaml)->toContain('# No deploy steps were generated — rerun app:pipeline with a deploy-hook host to add them.')
        ->and($yaml)->toContain('    develop:')
        ->and($yaml)->toContain('- step: *test')
        ->and($yaml)->not->toContain('deployment:')
        ->and($yaml)->not->toContain('deploy-hook.sh')
        ->and($yaml)->not->toContain('DEPLOY_HOOK');
});

test('the none host drops deploy-hook.sh, the DEPLOY_HOOK secrets and the deploy guidance', function (): void {
    $plan = bitbucketPipelinePlan(['host' => DeployHookHost::NONE]);

    $paths = array_map(fn ($file) => $file->path, bitbucketGenerator()->files($plan));
    $names = array_map(fn ($secret) => $secret->name, bitbucketGenerator()->secrets($plan));
    $instructions = implode("\n", bitbucketGenerator()->instructions($plan));

    expect($paths)->not->toContain('scripts/ci/deploy-hook.sh')
        ->and($names)->toBe(['COMPOSER_AUTH'])
        ->and($instructions)->toContain('Enable Pipelines once')
        ->and($instructions)->toContain('Rerun app:pipeline with a deploy-hook host to add the deploy steps.')
        ->and($instructions)->not->toContain('DEPLOY_HOOK')
        ->and($instructions)->not->toContain('trigger: manual');
});

test('both providers ship byte-identical scripts and invoke them in the same order', function (): void {
    $plan = bitbucketPipelinePlan();

    $scriptsOf = function (array $files): array {
        $scripts = [];

        foreach ($files as $file) {
            if (str_starts_with($file->path, CiScripts::DIRECTORY.'/')) {
                $scripts[$file->path] = $file->contents;
            }
        }

        return $scripts;
    };

    $outputs = [
        'github' => (new GitHubActionsGenerator(new CiScripts))->files($plan),
        'bitbucket' => bitbucketGenerator()->files($plan),
    ];

    expect($scriptsOf($outputs['github']))->toBe($scriptsOf($outputs['bitbucket']));

    $invocations = [
        'bash scripts/ci/lint.sh',
        'bash scripts/ci/build.sh',
        'bash scripts/ci/test.sh',
        'bash scripts/ci/deploy-hook.sh development "${DEPLOY_HOOK:-}"',
        'bash scripts/ci/deploy-hook.sh staging "${DEPLOY_HOOK:-}"',
        'bash scripts/ci/deploy-hook.sh production "${DEPLOY_HOOK:-}"',
    ];

    foreach ($outputs as $provider => $files) {
        $yaml = $files[0]->contents;
        $offset = 0;

        foreach ($invocations as $invocation) {
            $position = strpos($yaml, $invocation, $offset);

            expect($position)->not->toBeFalse("[{$provider}] is missing '{$invocation}' (in order)");

            $offset = (int) $position + strlen($invocation);
        }
    }
});
