<?php

declare(strict_types=1);

use Igne\LaravelBootUp\Data\DeploymentPlan;
use Igne\LaravelBootUp\Data\DeployTask;
use Igne\LaravelBootUp\Data\PipelinePlan;
use Igne\LaravelBootUp\Enums\BuiltInProcess;
use Igne\LaravelBootUp\Enums\DeployHookHost;
use Igne\LaravelBootUp\Enums\DeploymentEnvironment;
use Igne\LaravelBootUp\Enums\PackageManager;
use Igne\LaravelBootUp\Pipelines\CiScripts;

function ciScriptsPlan(array $overrides = [], array $deploymentOverrides = []): PipelinePlan
{
    $deploymentDefaults = [
        'environment' => DeploymentEnvironment::Development,
        'migrate' => true,
        'finalize' => ['storage:link'],
        'beforeMigrations' => [],
        'afterMigrations' => [],
        'frontend' => true,
        'packageManager' => PackageManager::Npm,
        'restarts' => [BuiltInProcess::Queue],
    ];

    $defaults = [
        'deployment' => new DeploymentPlan(...array_merge($deploymentDefaults, $deploymentOverrides)),
        'nova' => true,
        'composerAuth' => true,
        'pint' => true,
        'phpVersion' => '8.4',
        'branchEnvironments' => [
            'develop' => 'development',
            'staging' => 'staging',
            'main' => 'production',
        ],
    ];

    return new PipelinePlan(...array_merge($defaults, $overrides));
}

test('deploy-hook.sh sends the fortrabbit User-Agent, retries transport errors only and checks the HTTP status', function (): void {
    $script = (new CiScripts)->deployHook();

    expect($script->path)->toBe('scripts/ci/deploy-hook.sh')
        ->and($script->executable)->toBeTrue()
        ->and($script->contents)->toBe(<<<'BASH'
#!/usr/bin/env bash
#
# Trigger a deploy webhook: deploy-hook.sh <environment> <url>
#
# Generated by igne-agency/laravel-boot-up — regenerate with `php artisan generate:pipeline`.
# Works with any HTTPS POST deploy hook (fortrabbit, Forge, Envoyer, Ploi, ...).
# The User-Agent header is required by fortrabbit — its webhook endpoint
# rejects curl's default agent with a 403 — and is harmless everywhere else.

set -euo pipefail

environment="${1:?Usage: deploy-hook.sh <environment> <url>}"
url="${2:-}"

if [ -z "$url" ]; then
  echo "No deploy hook configured for ${environment} — skipping deploy."
  exit 0
fi

case "$url" in
  https://*) ;;
  *) echo "Refusing to call a non-HTTPS deploy hook for ${environment}." >&2; exit 1 ;;
esac

echo "Triggering the ${environment} deploy hook..."

response="$(mktemp)"
trap 'rm -f "$response"' EXIT

# No --fail: curl must exit 0 on HTTP errors so the status is checked (and
# the body shown) here instead. --retry covers transport failures and
# transient HTTP errors (408/429/5xx); a hard rejection like a 403 is
# never retried, so a rejected call cannot double-deploy.
status="$(curl --silent --show-error \
  --connect-timeout 10 --max-time 120 \
  --retry 3 --retry-all-errors \
  --request POST \
  --header 'User-Agent: fortrabbit' \
  --output "$response" --write-out '%{http_code}' \
  "$url")"

echo "Deploy hook responded with HTTP ${status}:"
cat "$response"
echo

case "$status" in
  2*) echo "Deploy triggered for ${environment}." ;;
  *) echo "Deploy hook for ${environment} failed (HTTP ${status})." >&2; exit 1 ;;
esac

BASH);
});

test('bootstrap.sh installs composer, prepares the env, publishes nova and detects the package manager from lockfiles', function (): void {
    $script = (new CiScripts)->bootstrap(ciScriptsPlan());

    expect($script->path)->toBe('scripts/ci/bootstrap.sh')
        ->and($script->executable)->toBeTrue()
        ->and($script->contents)->toBe(<<<'BASH'
#!/usr/bin/env bash
#
# Install dependencies and prepare the CI environment (sourced by build.sh and test.sh).
#
# Generated by igne-agency/laravel-boot-up — regenerate with `php artisan generate:pipeline`.

set -euo pipefail

# Run from the repository root, wherever the script is invoked from.
cd "$(dirname "${BASH_SOURCE[0]}")/../.."

echo "==> Installing Composer dependencies"
composer install --no-interaction --prefer-dist --optimize-autoloader --no-progress

echo "==> Preparing the test environment"
cp .env.pipeline .env
mkdir -p storage/framework/cache storage/framework/sessions storage/framework/testing storage/framework/views

echo "==> Publishing Nova assets"
php artisan nova:publish

# The package manager is detected from the committed lockfile at run
# time, so switching lockfiles never requires regenerating this script.
detect_package_manager() {
  if [ -f bun.lock ] || [ -f bun.lockb ]; then echo bun
  elif [ -f yarn.lock ]; then echo yarn
  elif [ -f pnpm-lock.yaml ]; then echo pnpm
  else echo npm
  fi
}

PM="$(detect_package_manager)"
export PM

echo "==> Installing Node dependencies with ${PM}"
command -v "$PM" >/dev/null 2>&1 || npm i -g "$PM"

case "$PM" in
  bun) bun install --frozen-lockfile || bun install ;;
  yarn) yarn install --frozen-lockfile || yarn install ;;
  npm) npm ci || npm install ;;
  pnpm) pnpm install --frozen-lockfile || pnpm install ;;
esac

BASH);
});

test('test.sh builds the frontend and runs the baked test sequence', function (): void {
    $script = (new CiScripts)->test(ciScriptsPlan());

    expect($script->path)->toBe('scripts/ci/test.sh')
        ->and($script->contents)->toBe(<<<'BASH'
#!/usr/bin/env bash
#
# Run the test suite against the committed CI environment.
#
# Generated by igne-agency/laravel-boot-up — regenerate with `php artisan generate:pipeline`.

set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/bootstrap.sh"

echo "==> Building frontend assets with ${PM}"
"$PM" run build

echo "==> Running the test suite"
php artisan config:clear
php artisan storage:link
php artisan migrate --force
php artisan test

BASH);
});

test('build.sh builds the frontend and round-trips the framework caches', function (): void {
    $script = (new CiScripts)->build(ciScriptsPlan());

    expect($script->path)->toBe('scripts/ci/build.sh')
        ->and($script->contents)->toContain('source "$(dirname "${BASH_SOURCE[0]}")/bootstrap.sh"')
        ->and($script->contents)->toContain('"$PM" run build')
        ->and($script->contents)->toContain('php artisan optimize')
        ->and($script->contents)->toContain('php artisan optimize:clear');
});

test('lint.sh is a self-contained pint check', function (): void {
    $script = (new CiScripts)->lint(ciScriptsPlan());

    expect($script->path)->toBe('scripts/ci/lint.sh')
        ->and($script->contents)->toContain('composer install --no-interaction --prefer-dist --no-progress --no-scripts')
        ->and($script->contents)->toContain('vendor/bin/pint --test')
        ->and($script->contents)->not->toContain('bootstrap.sh');
});

test('a project without pint gets no lint script', function (): void {
    expect((new CiScripts)->lint(ciScriptsPlan(['pint' => false])))->toBeNull();
});

test('files returns every script, executable, under scripts/ci', function (): void {
    $files = (new CiScripts)->files(ciScriptsPlan());

    expect(array_map(fn ($file) => $file->path, $files))->toBe([
        'scripts/ci/bootstrap.sh',
        'scripts/ci/lint.sh',
        'scripts/ci/build.sh',
        'scripts/ci/test.sh',
        'scripts/ci/deploy-hook.sh',
    ])->and(array_map(fn ($file) => $file->executable, $files))->each->toBeTrue();
});

test('files skips deploy-hook.sh when the host is none', function (): void {
    $paths = array_map(fn ($file) => $file->path, (new CiScripts)->files(ciScriptsPlan(['host' => DeployHookHost::None])));

    expect($paths)->not->toContain('scripts/ci/deploy-hook.sh')
        ->and($paths)->toHaveCount(4);
});

test('files skips the lint script without pint', function (): void {
    $paths = array_map(fn ($file) => $file->path, (new CiScripts)->files(ciScriptsPlan(['pint' => false])));

    expect($paths)->not->toContain('scripts/ci/lint.sh')
        ->and($paths)->toHaveCount(4);
});

test('a project without nova skips the nova publish block', function (): void {
    $script = (new CiScripts)->bootstrap(ciScriptsPlan(['nova' => false]));

    expect($script->contents)->not->toContain('nova:publish');
});

test('a project without a frontend skips package manager detection and frontend builds', function (): void {
    $scripts = new CiScripts;
    $plan = ciScriptsPlan([], ['frontend' => false]);

    expect($scripts->bootstrap($plan)->contents)->not->toContain('detect_package_manager')
        ->and($scripts->build($plan)->contents)->not->toContain('run build')
        ->and($scripts->test($plan)->contents)->not->toContain('run build');
});

test('config toggles drop their lines from test.sh', function (): void {
    $script = (new CiScripts)->test(ciScriptsPlan([], ['migrate' => false, 'finalize' => []]));

    expect($script->contents)->not->toContain('migrate --force')
        ->and($script->contents)->not->toContain('storage:link');
});

test('project commands render around migrate with echoed descriptions', function (): void {
    $script = (new CiScripts)->test(ciScriptsPlan([], [
        'beforeMigrations' => [DeployTask::artisan('wayfinder:generate', 'Generating routes...')],
        'afterMigrations' => [DeployTask::composer('dump-autoload --optimize')],
    ]));

    $migrate = strpos($script->contents, 'php artisan migrate --force');

    expect(strpos($script->contents, 'echo "Generating routes..."'))->toBeLessThan($migrate)
        ->and(strpos($script->contents, 'php artisan wayfinder:generate'))->toBeLessThan($migrate)
        ->and(strpos($script->contents, 'composer dump-autoload --optimize'))->toBeGreaterThan($migrate);
});

test('before-deploy runs before migrate and after-deploy runs after it, before the test run', function (): void {
    $script = (new CiScripts)->test(ciScriptsPlan([], [
        'beforeDeploy' => [DeployTask::artisan('pennant:purge')],
        'afterDeploy' => [DeployTask::artisan('cache:warm')],
    ]))->contents;

    $migrate = strpos($script, 'php artisan migrate --force');

    expect(strpos($script, 'php artisan pennant:purge'))->toBeLessThan($migrate)
        ->and(strpos($script, 'php artisan cache:warm'))->toBeGreaterThan($migrate)
        ->and(strpos($script, 'php artisan cache:warm'))->toBeLessThan(strpos($script, 'php artisan test'));
});

test('package-manager project commands use the runtime $PM with a frontend and the configured manager without', function (): void {
    $scripts = new CiScripts;
    $command = ['beforeMigrations' => [DeployTask::packageManager('run generate')]];

    expect($scripts->test(ciScriptsPlan([], $command))->contents)->toContain('"$PM" run generate')
        ->and($scripts->test(ciScriptsPlan([], [...$command, 'frontend' => false, 'packageManager' => PackageManager::Pnpm]))->contents)
        ->toContain('pnpm run generate');
});

test('branchList renders the branches as prose', function (): void {
    $scripts = new CiScripts;

    expect($scripts->branchList(ciScriptsPlan()))->toBe('develop, staging and main')
        ->and($scripts->branchList(ciScriptsPlan(['branchEnvironments' => ['main' => 'production']])))->toBe('main');
});
