<?php

declare(strict_types=1);

use Igne\LaravelBootUp\Data\DeploymentPlan;
use Igne\LaravelBootUp\Data\PipelineJobStep;
use Igne\LaravelBootUp\Data\PipelinePlan;
use Igne\LaravelBootUp\Enums\DeployHookHost;
use Igne\LaravelBootUp\Enums\DeploymentEnvironment;
use Igne\LaravelBootUp\Enums\PackageManager;
use Igne\LaravelBootUp\Pipelines\CiScripts;
use Igne\LaravelBootUp\Pipelines\GitHubActionsGenerator;
use Igne\LaravelBootUp\Pipelines\PipelineExtensions;

function githubPipelinePlan(array $overrides = [], array $deploymentOverrides = []): PipelinePlan
{
    $deploymentDefaults = [
        'environment' => DeploymentEnvironment::Development,
        'migrate' => true,
        'finalize' => ['storage:link'],
        'beforeMigrations' => [],
        'afterMigrations' => [],
        'frontend' => true,
        'packageManager' => PackageManager::Npm,
        'restartQueues' => true,
    ];

    $defaults = [
        'deployment' => new DeploymentPlan(...array_merge($deploymentDefaults, $deploymentOverrides)),
        'nova' => true,
        'composerAuth' => true,
        'pint' => true,
        'phpVersion' => '8.4',
        'branchEnvironments' => [
            'develop' => 'development',
            'staging' => 'staging',
            'main' => 'production',
        ],
        'host' => DeployHookHost::Fortrabbit,
    ];

    return new PipelinePlan(...array_merge($defaults, $overrides));
}

function githubGenerator(): GitHubActionsGenerator
{
    return new GitHubActionsGenerator(new CiScripts);
}

test('injects configured extra steps before and after a job, with an env block', function (): void {
    $plan = githubPipelinePlan(['extensions' => new PipelineExtensions([
        new PipelineJobStep('prep', 'test', 'before', 'Prepare', 'echo prep'),
        new PipelineJobStep('notify', 'test', 'after', 'Notify', 'bash notify.sh', env: ['HOOK' => '${{ secrets.HOOK }}']),
    ])]);

    $yaml = githubGenerator()->files($plan)[0]->contents;

    expect($yaml)
        ->toContain('- name: Prepare')
        ->toContain('run: echo prep')
        ->toContain('- name: Notify')
        ->toContain('HOOK: ${{ secrets.HOOK }}')
        ->toContain('run: bash notify.sh');

    // before precedes the test script; after follows it.
    expect(strpos($yaml, 'echo prep'))->toBeLessThan(strpos($yaml, 'bash scripts/ci/test.sh'))
        ->and(strpos($yaml, 'bash notify.sh'))->toBeGreaterThan(strpos($yaml, 'bash scripts/ci/test.sh'));
});

test('a provider-scoped extra step does not render for a different provider', function (): void {
    $plan = githubPipelinePlan(['extensions' => new PipelineExtensions([
        new PipelineJobStep('bb-only', 'test', 'after', 'BB', 'echo bitbucket', provider: 'bitbucket'),
    ])]);

    expect(githubGenerator()->files($plan)[0]->contents)->not->toContain('echo bitbucket');
});

function githubWorkflow(PipelinePlan $plan): string
{
    return githubGenerator()->files($plan)[0]->contents;
}

test('renders the full workflow for a nova project with pint', function (): void {
    $yaml = githubWorkflow(githubPipelinePlan());

    expect($yaml)->toBe(<<<'YAML'
# CI/CD pipeline (GitHub Actions)
# Generated by igne-agency/laravel-boot-up — lives at .github/workflows/ci.yml.
# Checks run on pull requests and on pushes to develop, staging and main;
# a green push then triggers its environment's deploy hook via
# scripts/ci/deploy-hook.sh (skipped when DEPLOY_HOOK is unset).

name: CI/CD

on:
  push:
    branches: [develop, staging, main]
  pull_request:

permissions:
  contents: read

# Superseded pull-request runs are cancelled; push runs never are — they deploy.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, dom, fileinfo, sqlite3, pdo_sqlite
          coverage: none

      - name: Determine the composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

      - name: Cache composer dependencies
        uses: actions/cache@v5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-

      - name: Check the code style
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        run: bash scripts/ci/lint.sh

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v5

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, dom, fileinfo, sqlite3, pdo_sqlite
          coverage: none

      - name: Determine the composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

      - name: Cache composer dependencies
        uses: actions/cache@v5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-

      - name: Build the frontend and framework caches
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        run: bash scripts/ci/build.sh

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v5

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, dom, fileinfo, sqlite3, pdo_sqlite
          coverage: none

      - name: Determine the composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

      - name: Cache composer dependencies
        uses: actions/cache@v5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-

      - name: Run the test suite
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        run: bash scripts/ci/test.sh

  deploy-development:
    name: Deploy (development)
    needs: [lint, build, test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: development
    concurrency:
      group: deployment-development
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: scripts/ci

      - name: Trigger the development deploy hook
        env:
          DEPLOY_HOOK: ${{ secrets.DEPLOY_HOOK }}
        run: bash scripts/ci/deploy-hook.sh development "${DEPLOY_HOOK:-}"

  deploy-staging:
    name: Deploy (staging)
    needs: [lint, build, test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: staging
    concurrency:
      group: deployment-staging
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: scripts/ci

      - name: Trigger the staging deploy hook
        env:
          DEPLOY_HOOK: ${{ secrets.DEPLOY_HOOK }}
        run: bash scripts/ci/deploy-hook.sh staging "${DEPLOY_HOOK:-}"

  deploy-production:
    name: Deploy (production)
    needs: [lint, build, test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: production
    concurrency:
      group: deployment-production
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: scripts/ci

      - name: Trigger the production deploy hook
        env:
          DEPLOY_HOOK: ${{ secrets.DEPLOY_HOOK }}
        run: bash scripts/ci/deploy-hook.sh production "${DEPLOY_HOOK:-}"

YAML);
});

test('files lists the workflow first, then every shared script', function (): void {
    $paths = array_map(fn ($file) => $file->path, githubGenerator()->files(githubPipelinePlan()));

    expect($paths)->toBe([
        '.github/workflows/ci.yml',
        'scripts/ci/bootstrap.sh',
        'scripts/ci/lint.sh',
        'scripts/ci/build.sh',
        'scripts/ci/test.sh',
        'scripts/ci/deploy-hook.sh',
    ]);
});

test('a project without composer auth gets no COMPOSER_AUTH env block', function (): void {
    expect(githubWorkflow(githubPipelinePlan(['composerAuth' => false])))->not->toContain('COMPOSER_AUTH');
});

test('composer auth is wired in for any project when enabled, without nova', function (): void {
    expect(githubWorkflow(githubPipelinePlan(['nova' => false, 'composerAuth' => true])))
        ->toContain('COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}');
});

test('a project without pint gets no lint job and deploys wait on build and test only', function (): void {
    $yaml = githubWorkflow(githubPipelinePlan(['pint' => false]));

    expect($yaml)->not->toContain('lint:')
        ->and($yaml)->not->toContain('lint.sh')
        ->and($yaml)->toContain('needs: [build, test]');
});

test('custom branches drive the triggers and the per-environment deploy jobs', function (): void {
    $yaml = githubWorkflow(githubPipelinePlan([
        'branchEnvironments' => ['main' => 'production'],
    ]));

    expect($yaml)->toContain('branches: [main]')
        ->and($yaml)->toContain('# Checks run on pull requests and on pushes to main;')
        ->and($yaml)->toContain('deploy-production:')
        ->and($yaml)->toContain("if: github.event_name == 'push' && github.ref == 'refs/heads/main'")
        ->and($yaml)->toContain('environment: production')
        ->and($yaml)->not->toContain('deploy-development');
});

test('the php version from composer.json lands in setup-php', function (): void {
    expect(githubWorkflow(githubPipelinePlan(['phpVersion' => '8.3'])))->toContain("php-version: '8.3'");
});

test('secrets list a single DEPLOY_HOOK covering every environment plus COMPOSER_AUTH', function (): void {
    $secrets = githubGenerator()->secrets(githubPipelinePlan());

    expect(array_map(fn ($secret) => $secret->name, $secrets))
        ->toBe(['DEPLOY_HOOK', 'COMPOSER_AUTH'])
        ->and($secrets[0]->location)->toBe('each environment')
        ->and($secrets[0]->purpose)->toBe('triggers the deploy on a green push');

    $deployHook = implode("\n", $secrets[0]->details);

    expect($deployHook)->toContain('Configure a DEPLOY_HOOK for EACH environment: development, staging, production.')
        ->and($deployHook)->toContain('Settings → Environments → <environment> → Environment secrets')
        // Every environment's own value guidance is still listed under the one entry.
        ->and($deployHook)->toContain('development (deploys on push to develop):')
        ->and($deployHook)->toContain('staging (deploys on push to staging):')
        ->and($deployHook)->toContain('production (deploys on push to main):')
        ->and($deployHook)->toContain('https://api.fortrabbit.com/webhooks/environments/{app-env-id}/deploy/{secret}');

    expect($secrets[1]->location)->toBe('repository secrets')
        ->and($secrets[1]->purpose)->toBe('authenticates Composer for private/licensed packages')
        ->and(implode("\n", $secrets[1]->details))->toContain('Settings → Secrets and variables → Actions → Repository secrets')
        ->and(implode("\n", $secrets[1]->details))->toContain('"nova.laravel.com"');
});

test('a project without composer auth lists no COMPOSER_AUTH secret', function (): void {
    $names = array_map(fn ($secret) => $secret->name, githubGenerator()->secrets(githubPipelinePlan(['composerAuth' => false])));

    expect($names)->not->toContain('COMPOSER_AUTH');
});

function githubGuidance(PipelinePlan $plan): string
{
    return implode("\n", [
        ...array_merge([], ...array_map(fn ($secret) => $secret->details, githubGenerator()->secrets($plan))),
        ...githubGenerator()->notes($plan),
        ...githubGenerator()->instructions($plan),
    ]);
}

test('the fortrabbit host gets the dashboard path, the hook example and the user-agent note', function (): void {
    $guidance = githubGuidance(githubPipelinePlan(['host' => DeployHookHost::Fortrabbit]));

    expect($guidance)->toContain('fortrabbit dashboard')
        ->and($guidance)->toContain('https://api.fortrabbit.com/webhooks/environments/{app-env-id}/deploy/{secret}')
        ->and($guidance)->toContain('User-Agent: fortrabbit')
        ->and($guidance)->toContain('Lint, Build and Test');
});

test('the forge host gets the deployment trigger URL and no fortrabbit mentions', function (): void {
    $guidance = githubGuidance(githubPipelinePlan(['host' => DeployHookHost::Forge]));

    expect($guidance)->toContain('Deployment trigger URL')
        ->and($guidance)->not->toContain('fortrabbit');
});

test('the webhook host gets neutral guidance naming no host', function (): void {
    $guidance = githubGuidance(githubPipelinePlan(['host' => DeployHookHost::Webhook]));

    expect($guidance)->toContain("your host's HTTPS deploy hook URL for development")
        ->and($guidance)->not->toContain('fortrabbit')
        ->and($guidance)->not->toContain('Forge');
});

test('informational lines live in the notes block, not the next steps', function (): void {
    $plan = githubPipelinePlan(['host' => DeployHookHost::Fortrabbit]);

    $notes = implode("\n", githubGenerator()->notes($plan));
    $instructions = implode("\n", githubGenerator()->instructions($plan));

    expect($notes)->toContain('Branch protection: require the Lint, Build and Test checks.')
        ->and($notes)->toContain('User-Agent: fortrabbit')
        ->and($notes)->toContain("An unset DEPLOY_HOOK skips that environment's deploy")
        ->and($notes)->toContain('Deploying from other branches? Remap boot-up.pipeline.branches and regenerate.');

    expect($instructions)->toContain('Add the secrets above to your GitHub repository')
        ->and($instructions)->not->toContain('Branch protection')
        ->and($instructions)->not->toContain('Deploying from other branches')
        ->and($instructions)->not->toContain('approval gate');
});

test('the none host renders a checks-only workflow that still runs on pushes', function (): void {
    $yaml = githubWorkflow(githubPipelinePlan(['host' => DeployHookHost::None]));

    expect($yaml)->toContain('# Checks run on pull requests and on pushes to develop, staging and main.')
        ->and($yaml)->toContain('# No deploy jobs were generated — rerun generate:pipeline with a deploy-hook host to add them.')
        ->and($yaml)->toContain('# Superseded pull-request runs are cancelled; push runs never are.')
        ->and($yaml)->toContain('branches: [develop, staging, main]')
        ->and($yaml)->toContain('run: bash scripts/ci/test.sh')
        ->and($yaml)->not->toContain('deploy-hook.sh')
        ->and($yaml)->not->toContain('deploy-development')
        ->and($yaml)->not->toContain('environment:')
        ->and($yaml)->not->toContain('DEPLOY_HOOK');
});

test('the none host drops deploy-hook.sh, the DEPLOY_HOOK secrets and the deploy guidance', function (): void {
    $plan = githubPipelinePlan(['host' => DeployHookHost::None]);

    $paths = array_map(fn ($file) => $file->path, githubGenerator()->files($plan));
    $names = array_map(fn ($secret) => $secret->name, githubGenerator()->secrets($plan));
    $notes = implode("\n", githubGenerator()->notes($plan));
    $instructions = implode("\n", githubGenerator()->instructions($plan));

    expect($paths)->not->toContain('scripts/ci/deploy-hook.sh')
        ->and($names)->toBe(['COMPOSER_AUTH'])
        ->and($notes)->toContain('Branch protection: require the Lint, Build and Test checks.')
        ->and($notes)->not->toContain('DEPLOY_HOOK')
        ->and($instructions)->toContain('Rerun generate:pipeline with a deploy-hook host to add the deploy jobs.')
        ->and($instructions)->not->toContain('DEPLOY_HOOK')
        ->and($instructions)->not->toContain('approval gate');
});
