<?php

declare(strict_types=1);

use Igne\LaravelBootUp\Deploy\Scripts\DeploymentEnvironment;
use Igne\LaravelBootUp\Deploy\Scripts\DeploymentPlan;
use Igne\LaravelBootUp\Frontend\PackageManager;
use Igne\LaravelBootUp\Pipelines\CiScripts;
use Igne\LaravelBootUp\Pipelines\DeployHookHost;
use Igne\LaravelBootUp\Pipelines\GitHubActionsGenerator;
use Igne\LaravelBootUp\Pipelines\PipelinePlan;

function githubPipelinePlan(array $overrides = [], array $deploymentOverrides = []): PipelinePlan
{
    $deploymentDefaults = [
        'environment' => DeploymentEnvironment::DEVELOPMENT,
        'migrate' => true,
        'finalize' => ['storage:link'],
        'beforeMigrations' => [],
        'afterMigrations' => [],
        'frontend' => true,
        'packageManager' => PackageManager::NPM,
        'restartQueues' => true,
    ];

    $defaults = [
        'deployment' => new DeploymentPlan(...array_merge($deploymentDefaults, $deploymentOverrides)),
        'nova' => true,
        'pint' => true,
        'phpVersion' => '8.4',
        'branchEnvironments' => [
            'develop' => 'development',
            'staging' => 'staging',
            'main' => 'production',
        ],
        'host' => DeployHookHost::FORTRABBIT,
    ];

    return new PipelinePlan(...array_merge($defaults, $overrides));
}

function githubGenerator(): GitHubActionsGenerator
{
    return new GitHubActionsGenerator(new CiScripts);
}

function githubWorkflow(PipelinePlan $plan): string
{
    return githubGenerator()->files($plan)[0]->contents;
}

test('renders the full workflow for a nova project with pint', function (): void {
    $yaml = githubWorkflow(githubPipelinePlan());

    expect($yaml)->toBe(<<<'YAML'
# CI/CD pipeline (GitHub Actions)
# Generated by igne-agency/laravel-boot-up — lives at .github/workflows/ci.yml.
# Checks run on pull requests and on pushes to develop, staging and main;
# a green push then triggers its environment's deploy hook via
# scripts/ci/deploy-hook.sh (skipped when DEPLOY_HOOK is unset).

name: CI/CD

on:
  push:
    branches: [develop, staging, main]
  pull_request:

permissions:
  contents: read

# Superseded pull-request runs are cancelled; push runs never are — they deploy.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, dom, fileinfo, sqlite3, pdo_sqlite
          coverage: none

      - name: Determine the composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

      - name: Cache composer dependencies
        uses: actions/cache@v5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-

      - name: Check the code style
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        run: bash scripts/ci/lint.sh

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v5

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, dom, fileinfo, sqlite3, pdo_sqlite
          coverage: none

      - name: Determine the composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

      - name: Cache composer dependencies
        uses: actions/cache@v5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-

      - name: Build the frontend and framework caches
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        run: bash scripts/ci/build.sh

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v5

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, dom, fileinfo, sqlite3, pdo_sqlite
          coverage: none

      - name: Determine the composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

      - name: Cache composer dependencies
        uses: actions/cache@v5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-

      - name: Run the test suite
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        run: bash scripts/ci/test.sh

  deploy-development:
    name: Deploy (development)
    needs: [lint, build, test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: development
    concurrency:
      group: deployment-development
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: scripts/ci

      - name: Trigger the development deploy hook
        env:
          DEPLOY_HOOK: ${{ secrets.DEPLOY_HOOK }}
        run: bash scripts/ci/deploy-hook.sh development "${DEPLOY_HOOK:-}"

  deploy-staging:
    name: Deploy (staging)
    needs: [lint, build, test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: staging
    concurrency:
      group: deployment-staging
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: scripts/ci

      - name: Trigger the staging deploy hook
        env:
          DEPLOY_HOOK: ${{ secrets.DEPLOY_HOOK }}
        run: bash scripts/ci/deploy-hook.sh staging "${DEPLOY_HOOK:-}"

  deploy-production:
    name: Deploy (production)
    needs: [lint, build, test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: production
    concurrency:
      group: deployment-production
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: scripts/ci

      - name: Trigger the production deploy hook
        env:
          DEPLOY_HOOK: ${{ secrets.DEPLOY_HOOK }}
        run: bash scripts/ci/deploy-hook.sh production "${DEPLOY_HOOK:-}"

YAML);
});

test('files lists the workflow first, then every shared script', function (): void {
    $paths = array_map(fn ($file) => $file->path, githubGenerator()->files(githubPipelinePlan()));

    expect($paths)->toBe([
        '.github/workflows/ci.yml',
        'scripts/ci/bootstrap.sh',
        'scripts/ci/lint.sh',
        'scripts/ci/build.sh',
        'scripts/ci/test.sh',
        'scripts/ci/deploy-hook.sh',
    ]);
});

test('a project without nova gets no composer auth', function (): void {
    expect(githubWorkflow(githubPipelinePlan(['nova' => false])))->not->toContain('COMPOSER_AUTH');
});

test('a project without pint gets no lint job and deploys wait on build and test only', function (): void {
    $yaml = githubWorkflow(githubPipelinePlan(['pint' => false]));

    expect($yaml)->not->toContain('lint:')
        ->and($yaml)->not->toContain('lint.sh')
        ->and($yaml)->toContain('needs: [build, test]');
});

test('custom branches drive the triggers and the per-environment deploy jobs', function (): void {
    $yaml = githubWorkflow(githubPipelinePlan([
        'branchEnvironments' => ['main' => 'production'],
    ]));

    expect($yaml)->toContain('branches: [main]')
        ->and($yaml)->toContain('# Checks run on pull requests and on pushes to main;')
        ->and($yaml)->toContain('deploy-production:')
        ->and($yaml)->toContain("if: github.event_name == 'push' && github.ref == 'refs/heads/main'")
        ->and($yaml)->toContain('environment: production')
        ->and($yaml)->not->toContain('deploy-development');
});

test('the php version from composer.json lands in setup-php', function (): void {
    expect(githubWorkflow(githubPipelinePlan(['phpVersion' => '8.3'])))->toContain("php-version: '8.3'");
});

test('secrets list one environment-scoped DEPLOY_HOOK per branch and COMPOSER_AUTH for nova', function (): void {
    $secrets = githubGenerator()->secrets(githubPipelinePlan());

    expect(array_map(fn ($secret) => $secret->name, $secrets))
        ->toBe(['DEPLOY_HOOK', 'DEPLOY_HOOK', 'DEPLOY_HOOK', 'COMPOSER_AUTH'])
        ->and($secrets[0]->location)->toBe('development environment')
        ->and($secrets[0]->purpose)->toBe('deploys on push to develop')
        ->and(implode("\n", $secrets[0]->details))->toContain('Add under: Settings → Environments → development → Environment secrets')
        ->and(implode("\n", $secrets[0]->details))->toContain('https://api.fortrabbit.com/webhooks/environments/{app-env-id}/deploy/{secret}')
        ->and($secrets[3]->location)->toBe('repository secrets')
        ->and(implode("\n", $secrets[3]->details))->toContain('Settings → Secrets and variables → Actions → Repository secrets')
        ->and(implode("\n", $secrets[3]->details))->toContain('"nova.laravel.com"');
});

test('a project without nova lists no COMPOSER_AUTH secret', function (): void {
    $names = array_map(fn ($secret) => $secret->name, githubGenerator()->secrets(githubPipelinePlan(['nova' => false])));

    expect($names)->not->toContain('COMPOSER_AUTH');
});

function githubGuidance(PipelinePlan $plan): string
{
    return implode("\n", [
        ...array_merge(...array_map(fn ($secret) => $secret->details, githubGenerator()->secrets($plan))),
        ...githubGenerator()->instructions($plan),
    ]);
}

test('the fortrabbit host gets the dashboard path, the hook example and the user-agent note', function (): void {
    $guidance = githubGuidance(githubPipelinePlan(['host' => DeployHookHost::FORTRABBIT]));

    expect($guidance)->toContain('fortrabbit dashboard')
        ->and($guidance)->toContain('https://api.fortrabbit.com/webhooks/environments/{app-env-id}/deploy/{secret}')
        ->and($guidance)->toContain('User-Agent: fortrabbit')
        ->and($guidance)->toContain('Lint, Build and Test');
});

test('the forge host gets the deployment trigger URL and no fortrabbit mentions', function (): void {
    $guidance = githubGuidance(githubPipelinePlan(['host' => DeployHookHost::FORGE]));

    expect($guidance)->toContain('Deployment trigger URL')
        ->and($guidance)->not->toContain('fortrabbit');
});

test('the webhook host gets neutral guidance naming no host', function (): void {
    $guidance = githubGuidance(githubPipelinePlan(['host' => DeployHookHost::WEBHOOK]));

    expect($guidance)->toContain("your host's HTTPS deploy hook URL for development")
        ->and($guidance)->not->toContain('fortrabbit')
        ->and($guidance)->not->toContain('Forge');
});

test('the approval-gate instruction names the last configured environment', function (): void {
    $instructions = implode("\n", githubGenerator()->instructions(githubPipelinePlan([
        'branchEnvironments' => ['develop' => 'dev', 'master' => 'live'],
    ])));

    expect($instructions)->toContain('add required reviewers to the live environment')
        ->and($instructions)->toContain('Deploying from other branches? Remap boot-up.pipeline.branches and regenerate.')
        ->and($instructions)->not->toContain('production')
        ->and($instructions)->not->toContain('(e.g. main)');
});

test('an empty branch map drops the approval-gate instruction', function (): void {
    $instructions = implode("\n", githubGenerator()->instructions(githubPipelinePlan(['branchEnvironments' => []])));

    expect($instructions)->not->toContain('approval gate');
});

test('the none host renders a checks-only workflow that still runs on pushes', function (): void {
    $yaml = githubWorkflow(githubPipelinePlan(['host' => DeployHookHost::NONE]));

    expect($yaml)->toContain('# Checks run on pull requests and on pushes to develop, staging and main.')
        ->and($yaml)->toContain('# No deploy jobs were generated — rerun app:pipeline with a deploy-hook host to add them.')
        ->and($yaml)->toContain('# Superseded pull-request runs are cancelled; push runs never are.')
        ->and($yaml)->toContain('branches: [develop, staging, main]')
        ->and($yaml)->toContain('run: bash scripts/ci/test.sh')
        ->and($yaml)->not->toContain('deploy-hook.sh')
        ->and($yaml)->not->toContain('deploy-development')
        ->and($yaml)->not->toContain('environment:')
        ->and($yaml)->not->toContain('DEPLOY_HOOK');
});

test('the none host drops deploy-hook.sh, the DEPLOY_HOOK secrets and the deploy guidance', function (): void {
    $plan = githubPipelinePlan(['host' => DeployHookHost::NONE]);

    $paths = array_map(fn ($file) => $file->path, githubGenerator()->files($plan));
    $names = array_map(fn ($secret) => $secret->name, githubGenerator()->secrets($plan));
    $instructions = implode("\n", githubGenerator()->instructions($plan));

    expect($paths)->not->toContain('scripts/ci/deploy-hook.sh')
        ->and($names)->toBe(['COMPOSER_AUTH'])
        ->and($instructions)->toContain('Branch protection: require the Lint, Build and Test checks.')
        ->and($instructions)->toContain('Rerun app:pipeline with a deploy-hook host to add the deploy jobs.')
        ->and($instructions)->not->toContain('DEPLOY_HOOK')
        ->and($instructions)->not->toContain('approval gate');
});
