<?php

declare(strict_types=1);

use Igne\LaravelBootstrap\Deploy\ProjectCommand;
use Igne\LaravelBootstrap\Deploy\Scripts\DeploymentEnvironment;
use Igne\LaravelBootstrap\Deploy\Scripts\DeploymentPlan;
use Igne\LaravelBootstrap\Frontend\PackageManager;
use Igne\LaravelBootstrap\Pipelines\GitHubActionsGenerator;
use Igne\LaravelBootstrap\Pipelines\PipelinePlan;
use Igne\LaravelBootstrap\Pipelines\PipelineSteps;

function githubPipelinePlan(array $overrides = [], array $deploymentOverrides = []): PipelinePlan
{
    $deploymentDefaults = [
        'environment' => DeploymentEnvironment::DEVELOPMENT,
        'migrate' => true,
        'finalize' => ['storage:link'],
        'beforeMigrations' => [],
        'afterMigrations' => [],
        'frontend' => true,
        'packageManager' => PackageManager::NPM,
        'restartQueues' => true,
    ];

    $defaults = [
        'deployment' => new DeploymentPlan(...array_merge($deploymentDefaults, $deploymentOverrides)),
        'nova' => true,
        'phpVersion' => '8.4',
        'branchHooks' => [
            'develop' => 'DEV_DEPLOY',
            'staging' => 'STAGING_DEPLOY',
            'master' => 'PROD_DEPLOY',
        ],
    ];

    return new PipelinePlan(...array_merge($defaults, $overrides));
}

function githubGenerator(): GitHubActionsGenerator
{
    return new GitHubActionsGenerator(new PipelineSteps);
}

test('renders the full workflow for a nova project with a frontend', function (): void {
    $yaml = githubGenerator()->generate(githubPipelinePlan());

    expect($yaml)->toBe(<<<'YAML'
# CI/CD pipeline (GitHub Actions)
# Generated by igne-agency/laravel-bootstrap — lives at .github/workflows/ci.yml.
# Tests run on pull requests and on pushes to develop, staging and master;
# pushes then trigger the matching deploy webhook (skipped when its secret is unset).

name: CI

on:
  push:
    branches: [develop, staging, master]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install-test:
    name: Install & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, dom, fileinfo, sqlite3, pdo_sqlite
          coverage: none

      - name: Determine the composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

      - name: Cache composer dependencies
        uses: actions/cache@v5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-

      - name: Install composer dependencies
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-progress

      - name: Prepare the test environment
        run: |
          cp .env.pipeline .env
          mkdir -p storage/framework/cache storage/framework/sessions storage/framework/testing storage/framework/views

      - name: Publish Nova assets
        run: php artisan nova:publish

      - name: Build frontend assets
        run: |
          npm ci || npm install
          npm run build

      - name: Run the test suite
        run: |
          php artisan config:clear
          php artisan storage:link
          php artisan migrate --force
          php artisan test

  deploy:
    name: Deploy
    needs: install-test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger the deploy webhook
        env:
          DEV_DEPLOY: ${{ secrets.DEV_DEPLOY }}
          STAGING_DEPLOY: ${{ secrets.STAGING_DEPLOY }}
          PROD_DEPLOY: ${{ secrets.PROD_DEPLOY }}
        run: |
          case "$GITHUB_REF_NAME" in
            develop) hook="$DEV_DEPLOY"; secret="DEV_DEPLOY" ;;
            staging) hook="$STAGING_DEPLOY"; secret="STAGING_DEPLOY" ;;
            master) hook="$PROD_DEPLOY"; secret="PROD_DEPLOY" ;;
            *) echo "Branch $GITHUB_REF_NAME does not deploy — skipping."; exit 0 ;;
          esac
          if [ -z "$hook" ]; then echo "$secret is not set — skipping deploy for $GITHUB_REF_NAME."; exit 0; fi
          curl --silent --show-error --fail-with-body -X POST "$hook"

YAML);
});

test('a project without nova gets no composer auth and no nova publish', function (): void {
    $yaml = githubGenerator()->generate(githubPipelinePlan(['nova' => false]));

    expect($yaml)->not->toContain('COMPOSER_AUTH')
        ->and($yaml)->not->toContain('nova:publish');
});

test('a project without a frontend gets no build step', function (): void {
    $yaml = githubGenerator()->generate(githubPipelinePlan([], ['frontend' => false]));

    expect($yaml)->not->toContain('Build frontend assets')
        ->and($yaml)->not->toContain('run build');
});

test('each package manager gets its lockfile-strict install line', function (PackageManager $manager, string $line): void {
    $yaml = githubGenerator()->generate(githubPipelinePlan([], ['packageManager' => $manager]));

    expect($yaml)->toContain($line)
        ->and($yaml)->toContain("{$manager->value} run build");

    if ($manager !== PackageManager::NPM) {
        expect($yaml)->toContain("npm i -g {$manager->value}");
    }
})->with([
    'npm' => [PackageManager::NPM, 'npm ci || npm install'],
    'pnpm' => [PackageManager::PNPM, 'pnpm install --frozen-lockfile || pnpm install'],
    'yarn' => [PackageManager::YARN, 'yarn install --frozen-lockfile || yarn install'],
    'bun' => [PackageManager::BUN, 'bun install --frozen-lockfile || bun install'],
]);

test('config toggles drop their lines', function (): void {
    $yaml = githubGenerator()->generate(githubPipelinePlan([], ['migrate' => false, 'finalize' => []]));

    expect($yaml)->not->toContain('migrate --force')
        ->and($yaml)->not->toContain('storage:link');
});

test('project commands render around migrate with echoed descriptions', function (): void {
    $yaml = githubGenerator()->generate(githubPipelinePlan([], [
        'beforeMigrations' => [ProjectCommand::artisan('wayfinder:generate', 'Generating routes...')],
        'afterMigrations' => [ProjectCommand::composer('dump-autoload --optimize')],
    ]));

    $migrate = strpos($yaml, 'php artisan migrate --force');

    expect(strpos($yaml, 'echo "Generating routes..."'))->toBeLessThan($migrate)
        ->and(strpos($yaml, 'php artisan wayfinder:generate'))->toBeLessThan($migrate)
        ->and(strpos($yaml, 'composer dump-autoload --optimize'))->toBeGreaterThan($migrate);
});

test('custom branch hooks drive the triggers, the case arms and the secret map', function (): void {
    $yaml = githubGenerator()->generate(githubPipelinePlan([
        'branchHooks' => ['main' => 'PROD_DEPLOY'],
    ]));

    expect($yaml)->toContain('branches: [main]')
        ->and($yaml)->toContain('# Tests run on pull requests and on pushes to main;')
        ->and($yaml)->toContain('main) hook="$PROD_DEPLOY"; secret="PROD_DEPLOY" ;;')
        ->and($yaml)->toContain('PROD_DEPLOY: ${{ secrets.PROD_DEPLOY }}')
        ->and($yaml)->not->toContain('DEV_DEPLOY');
});

test('the php version from composer.json lands in setup-php', function (): void {
    $yaml = githubGenerator()->generate(githubPipelinePlan(['phpVersion' => '8.3']));

    expect($yaml)->toContain("php-version: '8.3'");
});
