<?php

declare(strict_types=1);

namespace Igne\LaravelBootUp\Deploy\Scripts;

use Igne\LaravelBootUp\Deploy\ProjectCommand;
use Igne\LaravelBootUp\Support\Lines;

/**
 * Renders a Laravel Forge deployment script: the zero-downtime release
 * flow by default (Forge's current default for new sites), or the classic
 * git-pull flow for older sites — the release macros cannot be pasted
 * into a classic site, and vice versa.
 */
final class ForgeScriptGenerator implements ScriptGenerator
{
    public function key(): string
    {
        return 'forge';
    }

    public function label(): string
    {
        return 'Laravel Forge';
    }

    public function generate(DeploymentPlan $plan): string
    {
        return $plan->zeroDowntime
            ? $this->zeroDowntime($plan)
            : $this->classic($plan);
    }

    private function zeroDowntime(DeploymentPlan $plan): string
    {
        return Lines::make()
            ->comment(
                "Laravel Forge deployment script ({$plan->environment->value}, zero-downtime)",
                'Generated by igne-agency/laravel-boot-up — paste into Forge → your site → Deployments.',
                'Requires a site created WITH zero-downtime deployments; the $CREATE_RELEASE()/$ACTIVATE_RELEASE()',
                'macros do not work on classic sites (regenerate with --classic for those).',
            )
            ->lineWithBreak('$CREATE_RELEASE()')
            ->lineWithBreak('cd $FORGE_RELEASE_DIRECTORY')
            ->lineWithBreak($this->composerInstall($plan))
            ->linesWithBreak($this->artisanBlock($plan, '$FORGE_PHP'))
            ->when($plan->frontend, fn (Lines $script) => $script
                ->linesWithBreak($plan->packageManager->buildScriptLines(ensureInstalled: false)))
            ->lineWithBreak('$ACTIVATE_RELEASE()')
            // afterDeploy runs post-swap: the symlink now points at this release.
            ->when($plan->afterDeploy !== [], fn (Lines $script) => $script
                ->blank()
                ->lines($this->projectCommands($plan->afterDeploy, $plan)))
            ->lineWithBreakIf($plan->restartQueues, '$RESTART_QUEUES()')
            ->render();
    }

    private function classic(DeploymentPlan $plan): string
    {
        return Lines::make()
            ->comment(
                "Laravel Forge deployment script ({$plan->environment->value}, classic)",
                'Generated by igne-agency/laravel-boot-up — paste into Forge → your site → Deployments.',
                'For sites WITHOUT zero-downtime deployments (no release macros available).',
            )
            ->lineWithBreak('cd $FORGE_SITE_PATH')
            ->lineWithBreak('git pull origin $FORGE_SITE_BRANCH')
            ->lineWithBreak($this->composerInstall($plan))
            ->linesWithBreak($this->artisanBlock($plan, '$FORGE_PHP'))
            ->when($plan->frontend, fn (Lines $script) => $script
                ->linesWithBreak($plan->packageManager->buildScriptLines(ensureInstalled: false)))
            ->when($plan->afterDeploy !== [], fn (Lines $script) => $script
                ->linesWithBreak($this->projectCommands($plan->afterDeploy, $plan)))
            ->lineWithBreakIf($plan->restartQueues, '$FORGE_PHP artisan queue:restart')
            ->blank()
            ->comment('Prevent concurrent PHP-FPM reloads...')
            ->line('touch /tmp/fpmlock 2>/dev/null || true')
            ->lineWithBreak('(')
            ->indent(4, fn (Lines $script) => $script
                ->line('flock -w 10 9 || exit 1')
                ->lineWithBreak("echo 'Reloading PHP-FPM...'")
                ->line('sudo -S service $FORGE_PHP_FPM reload'))
            ->line(') 9</tmp/fpmlock')
            ->render();
    }

    private function composerInstall(DeploymentPlan $plan): string
    {
        $noDev = $plan->environment->includeDevDependencies() ? '' : ' --no-dev';

        return "\$FORGE_COMPOSER install{$noDev} --no-interaction --prefer-dist --optimize-autoloader";
    }

    private function artisanBlock(DeploymentPlan $plan, string $php): Lines
    {
        return Lines::make()
            ->lines($this->projectCommands($plan->beforeDeploy, $plan))
            ->lineIf($plan->environment->optimize(), "{$php} artisan optimize")
            ->each($plan->finalize, fn (Lines $script, string $command) => $script
                ->line("{$php} artisan {$command}"))
            ->lines($this->projectCommands($plan->beforeMigrations, $plan))
            ->lineIf($plan->migrate, "{$php} artisan migrate --force")
            ->lines($this->projectCommands($plan->afterMigrations, $plan));
    }

    /**
     * @param  list<ProjectCommand>  $commands
     */
    private function projectCommands(array $commands, DeploymentPlan $plan): Lines
    {
        return Lines::make()->each(
            $commands,
            fn (Lines $script, ProjectCommand $command) => $script->lines($this->projectCommand($command, $plan)),
        );
    }

    private function projectCommand(ProjectCommand $command, DeploymentPlan $plan): Lines
    {
        return Lines::make()
            ->lineIf($command->description !== null, "# {$command->description}")
            ->line($command->shellLine('$FORGE_PHP artisan', '$FORGE_COMPOSER', $plan->packageManager->value));
    }
}
