<?php

declare(strict_types=1);

namespace Igne\LaravelBootUp\Deploy\Scripts;

use Igne\LaravelBootUp\Deploy\ProjectCommand;

/**
 * Renders a Laravel Forge deployment script: the zero-downtime release
 * flow by default (Forge's current default for new sites), or the classic
 * git-pull flow for older sites — the release macros cannot be pasted
 * into a classic site, and vice versa.
 */
final class ForgeScriptGenerator implements ScriptGenerator
{
    public function key(): string
    {
        return 'forge';
    }

    public function label(): string
    {
        return 'Laravel Forge';
    }

    public function generate(DeploymentPlan $plan): string
    {
        return $plan->zeroDowntime
            ? $this->zeroDowntime($plan)
            : $this->classic($plan);
    }

    private function zeroDowntime(DeploymentPlan $plan): string
    {
        $lines = [
            "# Laravel Forge deployment script ({$plan->environment->value}, zero-downtime)",
            '# Generated by igne-agency/laravel-boot-up — paste into Forge → your site → Deployments.',
            '# Requires a site created WITH zero-downtime deployments; the $CREATE_RELEASE()/$ACTIVATE_RELEASE()',
            '# macros do not work on classic sites (regenerate with --classic for those).',
            '',
            '$CREATE_RELEASE()',
            '',
            'cd $FORGE_RELEASE_DIRECTORY',
            '',
            $this->composerInstall($plan),
            '',
            ...$this->artisanBlock($plan, '$FORGE_PHP'),
            ...$this->frontendBlock($plan),
            '',
            '$ACTIVATE_RELEASE()',
        ];

        if ($plan->restartQueues) {
            $lines[] = '';
            $lines[] = '$RESTART_QUEUES()';
        }

        return $this->render($lines);
    }

    private function classic(DeploymentPlan $plan): string
    {
        $lines = [
            "# Laravel Forge deployment script ({$plan->environment->value}, classic)",
            '# Generated by igne-agency/laravel-boot-up — paste into Forge → your site → Deployments.',
            '# For sites WITHOUT zero-downtime deployments (no release macros available).',
            '',
            'cd $FORGE_SITE_PATH',
            '',
            'git pull origin $FORGE_SITE_BRANCH',
            '',
            $this->composerInstall($plan),
            '',
            ...$this->artisanBlock($plan, '$FORGE_PHP'),
            ...$this->frontendBlock($plan),
        ];

        if ($plan->restartQueues) {
            $lines[] = '';
            $lines[] = '$FORGE_PHP artisan queue:restart';
        }

        $lines[] = '';
        $lines[] = '# Prevent concurrent PHP-FPM reloads...';
        $lines[] = 'touch /tmp/fpmlock 2>/dev/null || true';
        $lines[] = '';
        $lines[] = '(';
        $lines[] = '    flock -w 10 9 || exit 1';
        $lines[] = '';
        $lines[] = "    echo 'Reloading PHP-FPM...'";
        $lines[] = '    sudo -S service $FORGE_PHP_FPM reload';
        $lines[] = ') 9</tmp/fpmlock';

        return $this->render($lines);
    }

    private function composerInstall(DeploymentPlan $plan): string
    {
        $noDev = $plan->environment->includeDevDependencies() ? '' : ' --no-dev';

        return "\$FORGE_COMPOSER install{$noDev} --no-interaction --prefer-dist --optimize-autoloader";
    }

    /**
     * @return list<string>
     */
    private function artisanBlock(DeploymentPlan $plan, string $php): array
    {
        $lines = [];

        if ($plan->environment->optimize()) {
            $lines[] = "{$php} artisan optimize";
        }

        foreach ($plan->finalize as $command) {
            $lines[] = "{$php} artisan {$command}";
        }

        foreach ($plan->beforeMigrations as $command) {
            $lines = [...$lines, ...$this->projectCommand($command, $plan)];
        }

        if ($plan->migrate) {
            $lines[] = "{$php} artisan migrate --force";
        }

        foreach ($plan->afterMigrations as $command) {
            $lines = [...$lines, ...$this->projectCommand($command, $plan)];
        }

        return $lines;
    }

    /**
     * @return list<string>
     */
    private function frontendBlock(DeploymentPlan $plan): array
    {
        if (! $plan->frontend) {
            return [];
        }

        return ['', ...$plan->packageManager->buildScriptLines(ensureInstalled: false)];
    }

    /**
     * @return list<string>
     */
    private function projectCommand(ProjectCommand $command, DeploymentPlan $plan): array
    {
        $lines = [];

        if ($command->description !== null) {
            $lines[] = "# {$command->description}";
        }

        $lines[] = $command->shellLine('$FORGE_PHP artisan', '$FORGE_COMPOSER', $plan->packageManager->value);

        return $lines;
    }

    /**
     * @param  list<string>  $lines
     */
    private function render(array $lines): string
    {
        return implode("\n", $lines)."\n";
    }
}
