<?php

declare(strict_types=1);

namespace Igne\LaravelBootUp\Deploy\Scripts;

use Igne\LaravelBootUp\Deploy\ProjectCommand;
use Igne\LaravelBootUp\Support\Lines;

/**
 * Renders the two command lists Fortrabbit's dashboard expects per
 * environment: "Build commands" (run after git receives the push, before
 * the release — Composer preinstalled, Node available) and "Post deploy
 * commands" (run sequentially after the release is live).
 */
final class FortrabbitScriptGenerator implements ScriptGenerator
{
    public function key(): string
    {
        return 'fortrabbit';
    }

    public function label(): string
    {
        return 'Fortrabbit';
    }

    public function generate(DeploymentPlan $plan): string
    {
        return Lines::make()
            ->comment(
                "Fortrabbit deployment commands ({$plan->environment->value})",
                'Generated by igne-agency/laravel-boot-up.',
                'Paste each section into the fortrabbit dashboard → your App →',
                "Deployment settings for the {$plan->environment->value} environment.",
            )
            ->blank()
            ->comment('─── Build commands ────────────────────────────────────────────')
            ->line($this->composerInstall($plan))
            ->when($plan->frontend, fn (Lines $script) => $script
                ->lines($plan->packageManager->buildScriptLines(ensureInstalled: true)))
            ->blank()
            ->comment('─── Post deploy commands ──────────────────────────────────────')
            ->lines($this->postDeployCommands($plan))
            ->render();
    }

    private function composerInstall(DeploymentPlan $plan): string
    {
        $noDev = $plan->environment->includeDevDependencies() ? '' : ' --no-dev';

        return "composer install{$noDev} --prefer-dist --no-interaction --no-ansi --no-progress";
    }

    private function postDeployCommands(DeploymentPlan $plan): Lines
    {
        return Lines::make()
            ->lines($this->projectCommands($plan->beforeDeploy, $plan))
            ->lines($this->projectCommands($plan->beforeMigrations, $plan))
            ->lineIf($plan->migrate, 'php artisan migrate --force')
            ->lines($this->projectCommands($plan->afterMigrations, $plan))
            ->lineIf($plan->environment->optimize(), 'php artisan optimize')
            ->each($plan->finalize, fn (Lines $script, string $command) => $script
                ->line("php artisan {$command}"))
            ->lines($this->projectCommands($plan->afterDeploy, $plan))
            ->lineIf($plan->restartQueues, 'php artisan queue:restart');
    }

    /**
     * @param  list<ProjectCommand>  $commands
     */
    private function projectCommands(array $commands, DeploymentPlan $plan): Lines
    {
        return Lines::make()->each(
            $commands,
            fn (Lines $script, ProjectCommand $command) => $script->lines($this->projectCommand($command, $plan)),
        );
    }

    private function projectCommand(ProjectCommand $command, DeploymentPlan $plan): Lines
    {
        return Lines::make()
            ->lineIf($command->description !== null, "# {$command->description}")
            ->line($command->shellLine('php artisan', 'composer', $plan->packageManager->value));
    }
}
