<?php

declare(strict_types=1);

namespace Igne\LaravelBootUp\Deploy\Scripts;

use Igne\LaravelBootUp\Deploy\ProjectCommand;

/**
 * Renders the two command lists Fortrabbit's dashboard expects per
 * environment: "Build commands" (run after git receives the push, before
 * the release — Composer preinstalled, Node available) and "Post deploy
 * commands" (run sequentially after the release is live).
 */
final class FortrabbitScriptGenerator implements ScriptGenerator
{
    public function key(): string
    {
        return 'fortrabbit';
    }

    public function label(): string
    {
        return 'Fortrabbit';
    }

    public function generate(DeploymentPlan $plan): string
    {
        $lines = [
            "# Fortrabbit deployment commands ({$plan->environment->value})",
            '# Generated by igne-agency/laravel-boot-up.',
            '# Paste each section into the fortrabbit dashboard → your App →',
            "# Deployment settings for the {$plan->environment->value} environment.",
            '',
            '# ─── Build commands ────────────────────────────────────────────',
            $this->composerInstall($plan),
            ...$this->buildCommands($plan),
            '',
            '# ─── Post deploy commands ──────────────────────────────────────',
            ...$this->postDeployCommands($plan),
        ];

        return implode("\n", $lines)."\n";
    }

    private function composerInstall(DeploymentPlan $plan): string
    {
        $noDev = $plan->environment->includeDevDependencies() ? '' : ' --no-dev';

        return "composer install{$noDev} --prefer-dist --no-interaction --no-ansi --no-progress";
    }

    /**
     * @return list<string>
     */
    private function buildCommands(DeploymentPlan $plan): array
    {
        if (! $plan->frontend) {
            return [];
        }

        return $plan->packageManager->buildScriptLines(ensureInstalled: true);
    }

    /**
     * @return list<string>
     */
    private function postDeployCommands(DeploymentPlan $plan): array
    {
        $lines = [];

        foreach ($plan->beforeMigrations as $command) {
            $lines = [...$lines, ...$this->projectCommand($command, $plan)];
        }

        if ($plan->migrate) {
            $lines[] = 'php artisan migrate --force';
        }

        foreach ($plan->afterMigrations as $command) {
            $lines = [...$lines, ...$this->projectCommand($command, $plan)];
        }

        if ($plan->environment->optimize()) {
            $lines[] = 'php artisan optimize';
        }

        foreach ($plan->finalize as $command) {
            $lines[] = "php artisan {$command}";
        }

        if ($plan->restartQueues) {
            $lines[] = 'php artisan queue:restart';
        }

        return $lines;
    }

    /**
     * @return list<string>
     */
    private function projectCommand(ProjectCommand $command, DeploymentPlan $plan): array
    {
        $lines = [];

        if ($command->description !== null) {
            $lines[] = "# {$command->description}";
        }

        $lines[] = $command->shellLine('php artisan', 'composer', $plan->packageManager->value);

        return $lines;
    }
}
