<?php

declare(strict_types=1);

namespace Igne\LaravelBootUp\Deploy\Scripts;

use Igne\LaravelBootUp\Contracts\ScriptGenerator;
use Igne\LaravelBootUp\Data\DeploymentPlan;
use Igne\LaravelBootUp\Data\Lines;

/**
 * Renders the two command lists Fortrabbit's dashboard expects per
 * environment: "Build commands" (run after git receives the push, before
 * the release — Composer preinstalled, Node available) and "Post deploy
 * commands" (run sequentially after the release is live).
 */
final class FortrabbitScriptGenerator implements ScriptGenerator
{
    private const COMPOSER_FLAGS = '--prefer-dist --no-interaction --no-ansi --no-progress';

    public function key(): string
    {
        return 'fortrabbit';
    }

    public function label(): string
    {
        return 'Fortrabbit';
    }

    public function generate(DeploymentPlan $plan): Lines
    {
        $snippets = new DeployScriptSnippets($plan, artisan: 'php artisan', composer: 'composer');

        return Lines::make()
            ->comment(
                "Fortrabbit deployment commands ({$plan->environment->value})",
                'Generated by igne-agency/laravel-boot-up.',
                'Paste each section into the fortrabbit dashboard → your App →',
                "Deployment settings for the {$plan->environment->value} environment.",
            )
            ->blank()
            ->heading('─── Build commands ────────────────────────────────────────────')
            ->line($snippets->composerInstall(self::COMPOSER_FLAGS))
            ->when($plan->frontend, fn (Lines $script) => $script
                ->lines($plan->packageManager->buildScriptLines(ensureInstalled: true)))
            ->blank()
            ->heading('─── Post deploy commands ──────────────────────────────────────')
            ->lines($this->postDeployCommands($snippets));
    }

    private function postDeployCommands(DeployScriptSnippets $snippets): Lines
    {
        $plan = $snippets->plan;

        return Lines::make()
            ->lines($snippets->deployTasks($plan->beforeDeploy))
            ->lines($snippets->deployTasks($plan->beforeMigrations))
            ->lineIf($plan->migrate, $snippets->artisan('migrate --force'))
            ->lines($snippets->deployTasks($plan->afterMigrations))
            ->lineIf($plan->environment->optimize(), $snippets->artisan('optimize'))
            ->each($plan->finalize, fn (Lines $script, string $command) => $script
                ->line($snippets->artisan($command)))
            ->lines($snippets->deployTasks($plan->afterDeploy))
            ->lineIf($plan->restartQueues, $snippets->artisan('queue:restart'));
    }
}
